### ISSUE TITLE
Compilation error after upgrade 3.3.6 to 3.3.7 regarding Ethernet

### ISSUE THREAD

**Issue by broxinagil** [espressif/arduino-esp32#12356]
### Board

ESP32P4 Dev Module

### Device Description

After upgrading from esp32 board 3.3.6 to 3.3.7 I'm getting a comple error on my current project.
Reverting to 3.3.6 compiles OK again.

\AppData\Local\Arduino15\packages\esp32\tools\esp32p4_es-libs\3.3.7/include/esp_eth/include/esp_eth_mac_esp.h:303:5: error: designator order for field 'eth_esp32_emac_config_t::emac_dataif_gpio' does not match declaration order in 'eth_esp32_emac_config_t'
  303 |     }
      |     ^
\Projects\Arduino\IP101-P4\TEST\sketch_feb11a\sketch_feb11a.ino:174:47: note: in expansion of macro 'ETH_ESP32_EMAC_DEFAULT_CONFIG'
  174 |   eth_esp32_emac_config_t esp32_emac_config = ETH_ESP32_EMAC_DEFAULT_CONFIG();

### Hardware Configuration

Waveshare ESP32-P4-ETH

### Version

v3.3.7

### Type

Bug

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

80 MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

After upgrading from esp32 board 3.3.6 to 3.3.7 I'm getting a comple error on my current project.
Reverting to 3.3.6 compiles OK again.

```
\AppData\Local\Arduino15\packages\esp32\tools\esp32p4_es-libs\3.3.7/include/esp_eth/include/esp_eth_mac_esp.h:303:5: error: designator order for field 'eth_esp32_emac_config_t::emac_dataif_gpio' does not match declaration order in 'eth_esp32_emac_config_t'
  303 |     }
      |     ^
\Projects\Arduino\IP101-P4\TEST\sketch_feb11a\sketch_feb11a.ino:174:47: note: in expansion of macro 'ETH_ESP32_EMAC_DEFAULT_CONFIG'
  174 |   eth_esp32_emac_config_t esp32_emac_config = ETH_ESP32_EMAC_DEFAULT_CONFIG();

```

### Sketch

```cpp
void setup() {
  Serial.begin(115200);
  delay(1000);

  ESP_ERROR_CHECK(esp_event_loop_create_default());

  eth_mac_config_t mac_config = ETH_MAC_DEFAULT_CONFIG();
  eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();
  phy_config.phy_addr = ETH_PHY_ADDR;
  phy_config.reset_gpio_num = ETH_RESET_PIN;


  eth_esp32_emac_config_t esp32_emac_config = ETH_ESP32_EMAC_DEFAULT_CONFIG();
  esp32_emac_config.smi_mdc_gpio_num = ETH_MDC_PIN;
  esp32_emac_config.smi_mdio_gpio_num = ETH_MDIO_PIN;

  esp_eth_mac_t *mac = esp_eth_mac_new_esp32(&esp32_emac_config, &mac_config);

  esp_eth_phy_t *phy = esp_eth_phy_new_ip101(&phy_config);

  esp_eth_config_t config = ETH_DEFAULT_CONFIG(mac, phy);
  ESP_ERROR_CHECK(esp_eth_driver_install(&config, &eth_handle));

  ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ESP_EVENT_ANY_ID, &eth_event_handler, NULL));

  ESP_ERROR_CHECK(esp_eth_update_input_path(eth_handle, raw_rx_cb, NULL));
  ESP_ERROR_CHECK(esp_eth_start(eth_handle));
  bool pena = true;
  esp_eth_ioctl(eth_handle, ETH_CMD_S_PROMISCUOUS, &pena);


  uint8_t maca[6];
  mac->get_addr(mac, maca);
  Serial.print("MAC is ");
  Serial.printf("%02X:%02X:%02X:%02X:%02X:%02X", maca[0], maca[1], maca[2], maca[3], maca[4], maca[5]);
  Serial.println();


}
```

### Debug Message

```plain
.
```

### Other Steps to Reproduce

After downgrade to 3.3.6 the app compiles successfully. Trying again with 3.3.7 produces same compile-error

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by broxinagil** [comment]
MIssed to add the header for example code

```
#include <Arduino.h>

extern "C" {
#include "esp_event.h"
#include "esp_eth.h"
#include "driver/gpio.h"
#include "esp_eth_com.h"
}

#define ETH_PHY_ADDR 1
#define ETH_MDC_PIN 31
#define ETH_MDIO_PIN 52
#define ETH_RESET_PIN 51  
```

**Comment by me-no-dev** [comment]
@broxinagil you are using the ESP-IDF APIs, not the Arduino ones. I suggest you have a look at the IDF documentation on how to properly use their APIs. Or you can use our Ethernet library

**Comment by broxinagil** [comment]
This happens after updating to esp32 3.3.7.  The "More Info" on the board-library points me to here !
If I go back to 3.3.6 the error is gone.

<img width="290" height="159" alt="Image" src="https://github.com/user-attachments/assets/20af5a5f-8765-47bc-84c5-2669007c7d4e" />

**Comment by me-no-dev** [comment]
Arduino does provide access to ESP-IDF APIs (and is built on top of them), but does not control them. They are subject to change between versions. That is why Arduino provides it's own APIs to make this simpler and safer for users.

**Comment by broxinagil** [comment]
I understand, but where then is the mistake ? Who is responsible for the Macro ETH_ESP32_EMAC_DEFAULT_CONFIG ? Because, what AI has discovered, it seems the Macro did not cover the changes made in the struct itself:

Why This Happens in 3.3.7
In ESP-IDF ≤5.1, eth_esp32_emac_config_t had smi_mdc_gpio_num and smi_mdio_gpio_num before emac_dataif_gpio.
In ESP-IDF 5.2 (used in Arduino-ESP32 3.3.7), emac_dataif_gpio was moved to the top of the struct.
The macro ETH_ESP32_EMAC_DEFAULT_CONFIG() still initializes in the old order, so GCC/Clang throws the “designator order” error.

**Comment by broxinagil** [comment]
Well, I see the macro is in the espressif headers. So seems their fault ;-)
Sorry bothering you. I'll revert to 3.3.6 for now and check idf for changes.

Thanks
