### ISSUE TITLE
Error Compiling... Arduino IDE version 1.8.19 ... Board Manager ... ESP32 Espressif System version 2.0.4 INSTALLED

### ISSUE THREAD

**Issue by rodyeo** [espressif/arduino-esp32#6996]
### Board

AI Thinker ESP32-CAM

### Device Description

ESP32-S

### Hardware Configuration

Standard programming pins used on 5V FTDI Serial Programmer

### Version

v2.0.4

### IDE Name

Arduino IDE version 1.8.19

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

Error Compiling...
Arduino IDE version 1.8.19
Examples\ESP32\Camera\CameraWebServer
Board Manager ... ESP32 Espressif System version 2.0.4 INSTALLED

Error never happen on ESP32 Espressif System version 2.0.3 previously.

Also notice brown out detector library is missing in version 2.0.4 please include it in next release.

#include "soc/soc.h" //disable brownout problems
#include "soc/rtc_cntl_reg.h" //disable brownout problems
WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable brownout detector

### Sketch

```cpp
#include "esp_camera.h"
#include <WiFi.h>

//
// WARNING!!! PSRAM IC required for UXGA resolution and high JPEG quality
//            Ensure ESP32 Wrover Module or other board with PSRAM is selected
//            Partial images will be transmitted if image exceeds buffer size
//
//            You must select partition scheme from the board menu that has at least 3MB APP space.
//            Face Recognition is DISABLED for ESP32 and ESP32-S2, because it takes up from 15 
//            seconds to process single frame. Face Detection is ENABLED if PSRAM is enabled as well

// ===================
// Select camera model
// ===================
//#define CAMERA_MODEL_WROVER_KIT // Has PSRAM
//#define CAMERA_MODEL_ESP_EYE // Has PSRAM
//#define CAMERA_MODEL_ESP32S3_EYE // Has PSRAM
//#define CAMERA_MODEL_M5STACK_PSRAM // Has PSRAM
//#define CAMERA_MODEL_M5STACK_V2_PSRAM // M5Camera version B Has PSRAM
//#define CAMERA_MODEL_M5STACK_WIDE // Has PSRAM
//#define CAMERA_MODEL_M5STACK_ESP32CAM // No PSRAM
//#define CAMERA_MODEL_M5STACK_UNITCAM // No PSRAM
#define CAMERA_MODEL_AI_THINKER // Has PSRAM
//#define CAMERA_MODEL_TTGO_T_JOURNAL // No PSRAM
// ** Espressif Internal Boards **
//#define CAMERA_MODEL_ESP32_CAM_BOARD
//#define CAMERA_MODEL_ESP32S2_CAM_BOARD
//#define CAMERA_MODEL_ESP32S3_CAM_LCD

#include "camera_pins.h"

// ===========================
// Enter your WiFi credentials
// ===========================
const char* ssid = "XXXXXXXXXX";
const char* password = "XXXXXXXXXXXXXXXXXXXX";

void startCameraServer();

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();

  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.frame_size = FRAMESIZE_UXGA;
  config.pixel_format = PIXFORMAT_JPEG; // for streaming
  //config.pixel_format = PIXFORMAT_RGB565; // for face detection/recognition
  config.grab_mode = CAMERA_GRAB_WHEN_EMPTY;
  config.fb_location = CAMERA_FB_IN_PSRAM;
  config.jpeg_quality = 12;
  config.fb_count = 1;
  
  // if PSRAM IC present, init with UXGA resolution and higher JPEG quality
  //                      for larger pre-allocated frame buffer.
  if(config.pixel_format == PIXFORMAT_JPEG){
    if(psramFound()){
      config.jpeg_quality = 10;
      config.fb_count = 2;
      config.grab_mode = CAMERA_GRAB_LATEST;
    } else {
      // Limit the frame size when PSRAM is not available
      config.frame_size = FRAMESIZE_SVGA;
      config.fb_location = CAMERA_FB_IN_DRAM;
    }
  } else {
    // Best option for face detection/recognition
    config.frame_size = FRAMESIZE_240X240;
#if CONFIG_IDF_TARGET_ESP32S3
    config.fb_count = 2;
#endif
  }

#if defined(CAMERA_MODEL_ESP_EYE)
  pinMode(13, INPUT_PULLUP);
  pinMode(14, INPUT_PULLUP);
#endif

  // camera init
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }

  sensor_t * s = esp_camera_sensor_get();
  // initial sensors are flipped vertically and colors are a bit saturated
  if (s->id.PID == OV3660_PID) {
    s->set_vflip(s, 1); // flip it back
    s->set_brightness(s, 1); // up the brightness just a bit
    s->set_saturation(s, -2); // lower the saturation
  }
  // drop down frame size for higher initial frame rate
  if(config.pixel_format == PIXFORMAT_JPEG){
    s->set_framesize(s, FRAMESIZE_QVGA);
  }

#if defined(CAMERA_MODEL_M5STACK_WIDE) || defined(CAMERA_MODEL_M5STACK_ESP32CAM)
  s->set_vflip(s, 1);
  s->set_hmirror(s, 1);
#endif

#if defined(CAMERA_MODEL_ESP32S3_EYE)
  s->set_vflip(s, 1);
#endif

  WiFi.begin(ssid, password);
  WiFi.setSleep(false);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");

  startCameraServer();

  Serial.print("Camera Ready! Use 'http://");
  Serial.print(WiFi.localIP());
  Serial.println("' to connect");
}

void loop() {
  // Do nothing. Everything is done in another task by the web server
  delay(10000);
}
```

### Debug Message

```plain
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp: In function 'void startCameraServer()':
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1213:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1213:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1213:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1219:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1219:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1219:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1225:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1225:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1225:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1231:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1231:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1231:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1237:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1237:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1237:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1243:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1243:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1243:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1249:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1249:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1249:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1255:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1255:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1255:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1261:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1261:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1261:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1267:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1267:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1267:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1273:25: warning: missing initializer for member 'httpd_uri::is_websocket' [-Wmissing-field-initializers]
         .user_ctx = NULL};
                         ^
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1273:25: warning: missing initializer for member 'httpd_uri::handle_ws_control_frames' [-Wmissing-field-initializers]
C:\Users\god\Documents\Arduino\CameraWebServer\app_httpd.cpp:1273:25: warning: missing initializer for member 'httpd_uri::supported_subprotocol' [-Wmissing-field-initializers]
```

### Other Steps to Reproduce

Click on Verify ... Error Compiling ...

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment]
@rodyeo - Please check #6993 

Let me know if this PR fixes this issue. Thanks.

**Comment by rodyeo** [comment]
> @rodyeo - Please check #6993
> 
> Let me know if this PR fixes this issue. Thanks.

I modified the "app_httpd.cpp" include file as per instructions and recompile with ESP32 Board Manager version 2.0.4 latest installed library with no compilation error. The problem have been is resolved! Thank you very much for the solution! You may safely commit this fix to the master branch for global users to install the new fixed CameraWebServer example source code. Thanks a million buddy! Cheers ;) Regards, Rodney Yeo @ http://rodyeo.dyndns.org

**Comment by rodyeo** [comment]
Updated fix at my social media page ... https://m.facebook.com/story.php?story_fbid=pfbid0y7DynNxnamRqpENxj4qJLqfP1oDTeTRMsHuqzb79E8FeShw9C3EnzteysC2AaWkYl&id=554017662

**Comment by rodyeo** [comment]
I shall close this case as resolved! Thanks everyone ;)
