### ISSUE TITLE
2.0.0-rc1 Undefined reference to `SHA1Update` and `SHA1Final`. 

### ISSUE THREAD

**Issue by CelliesProjects** [espressif/arduino-esp32#5457]
@me-no-dev 
If updated to 2.0.0-rc1 and compiling a project with ESPAsyncWebServer websocket code the compiler errors out on undefined references which come from [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer ) not finding `SHA1Update` and `SHA1Final`.

### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			2.0.0-rc1
IDE name:						Arduino IDE
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                       Ubuntu

### Description:
The 2.0.0-rc1  release cannot find `SHA1Update` and `SHA1Final` which are used by [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer ) websocket server.

The same code compiles fine in 1.0.5 - 1.0.6.

### Debug Messages:
```
o:(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x10): undefined reference to `SHA1Init'
/home/cellie/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r1/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /tmp/arduino_build_389171/libraries/ESPAsyncWebServer/AsyncWebSocket.cpp.o:(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x14): undefined reference to `SHA1Update'
/home/cellie/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r1/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /tmp/arduino_build_389171/libraries/ESPAsyncWebServer/AsyncWebSocket.cpp.o:(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x18): undefined reference to `SHA1Final'
/home/cellie/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r1/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /tmp/arduino_build_389171/libraries/ESPAsyncWebServer/AsyncWebSocket.cpp.o: in function `AsyncWebSocketResponse::AsyncWebSocketResponse(String const&, AsyncWebSocket*)':
```

**Comment by CelliesProjects** [comment]
Just saw #5427 which is about the same issue.

**Comment by CelliesProjects** [comment]
Seems the fix is to patch ESPAsyncWebServer. 
See https://github.com/me-no-dev/ESPAsyncWebServer/pull/999.

Closing this for now.
