### ISSUE TITLE
latest master and release 3.0.5 lib i2c slave compile fail with function implicit error

### ISSUE THREAD

**Issue by cqlhupt** [espressif/arduino-esp32#10486]
### Board

ESP32c3

### Device Description

ESP32c3

### Hardware Configuration

NA

### Version

latest master (checkout manually)

### IDE Name

vscode esp-ide arduino-as-component

### Operating System

Windows 10

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I had check the functions mention by the compile log, they are not been define in the file. I don't know what should I expect.

### Sketch

```cpp
// Please add an actual example sketch, not the source code of the slave lib
```

### Debug Message

```plain
[1401/1566] Building C object esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-i2c-slave.c.obj
FAILED: esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-i2c-slave.c.obj
E:\vstudio\esp32_tool\tools\riscv32-esp-elf\esp-13.2.0_20240530\riscv32-esp-elf\bin\riscv32-esp-elf-gcc.exe -DESP_PLATFORM -DIDF_VER=\"v5.3.1\" 
-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -IE:/vstudio/esp32_example_project/arduino-as-component_bk/build/config -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/variants/esp32c3 -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32 -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/ArduinoOTA/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/AsyncUDP/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/BLE/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/BluetoothSerial/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/DNSServer/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/EEPROM/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/ESP_I2S/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/ESP_NOW/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/ESP_SR/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/ESPmDNS/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Ethernet/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/FFat/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/FS/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/HTTPClient/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/HTTPUpdate/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Insights/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/LittleFS/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/NetBIOS/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Network/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/OpenThread/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/PPP/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Preferences/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/RainMaker/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/SD_MMC/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/SD/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/SimpleBLE/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/SPIFFS/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/SPI/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Ticker/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Update/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/USB/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/WebServer/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/NetworkClientSecure/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/WiFi/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/WiFiProv/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Wire/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/libraries/Zigbee/src -IE:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/libb64 -IE:/vstudio/esp32_container/esp-idf/components/newlib/platform_include -IE:/vstudio/esp32_container/esp-idf/components/freertos/config/include -IE:/vstudio/esp32_container/esp-idf/components/freertos/config/include/freertos -IE:/vstudio/esp32_container/esp-idf/components/freertos/config/riscv/include -IE:/vstudio/esp32_container/esp-idf/components/freertos/FreeRTOS-Kernel/include -IE:/vstudio/esp32_container/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include -IE:/vstudio/esp32_container/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos -IE:/vstudio/esp32_container/esp-idf/components/freertos/esp_additions/include -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/include -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/include/soc -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/include/soc/esp32c3 -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/dma/include -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/ldo/include -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/port/esp32c3/. -IE:/vstudio/esp32_container/esp-idf/components/esp_hw_support/port/esp32c3/include -IE:/vstudio/esp32_container/esp-idf/components/heap/include -IE:/vstudio/esp32_container/esp-idf/components/log/include -IE:/vstudio/esp32_container/esp-idf/components/soc/include -IE:/vstudio/esp32_container/esp-idf/components/soc/esp32c3 -IE:/vstudio/esp32_container/esp-idf/components/soc/esp32c3/include -IE:/vstudio/esp32_container/esp-idf/components/hal/platform_port/include -IE:/vstudio/esp32_container/esp-idf/components/hal/esp32c3/include -IE:/vstudio/esp32_container/esp-idf/components/hal/include -IE:/vstudio/esp32_container/esp-idf/components/esp_rom/include -IE:/vstudio/esp32_container/esp-idf/components/esp_rom/include/esp32c3 -IE:/vstudio/esp32_container/esp-idf/components/esp_rom/esp32c3 -IE:/vstudio/esp32_container/esp-idf/components/esp_common/include -IE:/vstudio/esp32_container/esp-idf/components/esp_system/include -IE:/vstudio/esp32_container/esp-idf/components/esp_system/port/soc -IE:/vstudio/esp32_container/esp-idf/components/esp_system/port/include/riscv -IE:/vstudio/esp32_container/esp-idf/components/esp_system/port/include/private -IE:/vstudio/esp32_container/esp-idf/components/riscv/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/include/apps -IE:/vstudio/esp32_container/esp-idf/components/lwip/include/apps/sntp -IE:/vstudio/esp32_container/esp-idf/components/lwip/lwip/src/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/port/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/port/freertos/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/port/esp32xx/include -IE:/vstudio/esp32_container/esp-idf/components/lwip/port/esp32xx/include/arch -IE:/vstudio/esp32_container/esp-idf/components/lwip/port/esp32xx/include/sys -IE:/vstudio/esp32_container/esp-idf/components/spi_flash/include -IE:/vstudio/esp32_container/esp-idf/components/esp_partition/include -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/port/include -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/mbedtls/include -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/mbedtls/library -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/esp_crt_bundle/include -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m -IE:/vstudio/esp32_container/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m/p256-m -IE:/vstudio/esp32_container/esp-idf/components/wpa_supplicant/include -IE:/vstudio/esp32_container/esp-idf/components/wpa_supplicant/port/include -IE:/vstudio/esp32_container/esp-idf/components/wpa_supplicant/esp_supplicant/include -IE:/vstudio/esp32_container/esp-idf/components/esp_adc/include -IE:/vstudio/esp32_container/esp-idf/components/esp_adc/interface -IE:/vstudio/esp32_container/esp-idf/components/esp_adc/esp32c3/include -IE:/vstudio/esp32_container/esp-idf/components/esp_adc/deprecated/include -IE:/vstudio/esp32_container/esp-idf/components/esp_eth/include -IE:/vstudio/esp32_container/esp-idf/components/esp_event/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_spi/include -IE:/vstudio/esp32_container/esp-idf/components/esp_pm/include -IE:/vstudio/esp32_container/esp-idf/components/http_parser -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__network_provisioning/include -IE:/vstudio/esp32_container/esp-idf/components/protocomm/include/common -IE:/vstudio/esp32_container/esp-idf/components/protocomm/include/security -IE:/vstudio/esp32_container/esp-idf/components/protocomm/include/transports -IE:/vstudio/esp32_container/esp-idf/components/protocomm/include/crypto/srp6a -IE:/vstudio/esp32_container/esp-idf/components/protocomm/proto-c -IE:/vstudio/esp32_container/esp-idf/components/esp_timer/include -IE:/vstudio/esp32_container/esp-idf/components/esp_wifi/include -IE:/vstudio/esp32_container/esp-idf/components/esp_wifi/wifi_apps/include -IE:/vstudio/esp32_container/esp-idf/components/esp_wifi/wifi_apps/nan_app/include -IE:/vstudio/esp32_container/esp-idf/components/esp_wifi/include/local -IE:/vstudio/esp32_container/esp-idf/components/esp_phy/include -IE:/vstudio/esp32_container/esp-idf/components/esp_phy/esp32c3/include -IE:/vstudio/esp32_container/esp-idf/components/esp_netif/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/chmorgan__esp-libhelix-mp3/libhelix-mp3/pub -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-modbus/freemodbus/common/include -IE:/vstudio/esp32_container/esp-idf/components/driver/deprecated -IE:/vstudio/esp32_container/esp-idf/components/driver/i2c/include -IE:/vstudio/esp32_container/esp-idf/components/driver/touch_sensor/include -IE:/vstudio/esp32_container/esp-idf/components/driver/twai/include -IE:/vstudio/esp32_container/esp-idf/components/esp_ringbuf/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_gpio/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_pcnt/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_gptimer/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_mcpwm/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_ana_cmpr/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_i2s/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_sdmmc/include -IE:/vstudio/esp32_container/esp-idf/components/sdmmc/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_sdspi/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_sdio/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_dac/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_rmt/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_tsens/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_sdm/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_i2c/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_uart/include -IE:/vstudio/esp32_container/esp-idf/components/vfs/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_ledc/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_parlio/include -IE:/vstudio/esp32_container/esp-idf/components/esp_driver_usb_serial_jtag/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__libsodium/libsodium/src/libsodium/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__libsodium/port_include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__mdns/include -IE:/vstudio/esp32_container/esp-idf/components/console -IE:/vstudio/esp32_container/esp-idf/components/esp_vfs_console/include -IE:/vstudio/esp32_container/esp-idf/components/fatfs/diskio -IE:/vstudio/esp32_container/esp-idf/components/fatfs/src -IE:/vstudio/esp32_container/esp-idf/components/fatfs/vfs -IE:/vstudio/esp32_container/esp-idf/components/wear_levelling/include -IE:/vstudio/esp32_container/esp-idf/components/nvs_flash/include -IE:/vstudio/esp32_container/esp-idf/components/app_update/include -IE:/vstudio/esp32_container/esp-idf/components/bootloader_support/include -IE:/vstudio/esp32_container/esp-idf/components/bootloader_support/bootloader_flash/include -IE:/vstudio/esp32_container/esp-idf/components/esp_app_format/include 
-IE:/vstudio/esp32_container/esp-idf/components/esp_bootloader_format/include -IE:/vstudio/esp32_container/esp-idf/components/spiffs/include -IE:/vstudio/esp32_container/esp-idf/components/esp_hid/include -IE:/vstudio/esp32_container/esp-idf/components/esp_psram/include -IE:/vstudio/esp32_container/esp-idf/components/esp_https_ota/include -IE:/vstudio/esp32_container/esp-idf/components/esp_http_client/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/dotprod/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/support/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/support/mem/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/hann/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/blackman/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/blackman_harris/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/blackman_nuttall/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/nuttall/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/windows/flat_top/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/iir/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/fir/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/add/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/sub/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/mul/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/addc/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/mulc/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/math/sqrt/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/mul/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/add/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/addc/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/mulc/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/sub/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/fft/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/dct/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/conv/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/common/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/matrix/mul/test/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/kalman/ekf/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-zboss-lib/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp-zigbee-lib/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp_insights/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp_diagnostics/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp_modem/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__esp_rainmaker/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__rmaker_common/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/espressif__qrcode/include -IE:/vstudio/esp32_example_project/arduino-as-component_bk/managed_components/joltwallet__littlefs/include -march=rv32imc_zicsr_zifencei  -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -nostartfiles -Og -fno-shrink-wrap -fmacro-prefix-map=E:/vstudio/esp32_example_project/arduino-as-component_bk=. -fmacro-prefix-map=E:/vstudio/esp32_container/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -DARDUINO=10812 -DARDUINO_ESP32C3_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD=\"ESP32C3_DEV\" -DARDUINO_VARIANT=\"esp32c3\" -DESP32=ESP32 -MD -MT esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-i2c-slave.c.obj -MF esp-idf\arduino\CMakeFiles\__idf_arduino.dir\cores\esp32\esp32-hal-i2c-slave.c.obj.d -o esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-i2c-slave.c.obj -c E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c: In function 'i2cSlaveInit':      
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c:319:3: error: implicit declaration of function 'i2c_ll_set_fifo_mode'; did you mean 'i2c_ll_set_data_mode'? [-Werror=implicit-function-declaration]
  319 |   i2c_ll_set_fifo_mode(i2c->dev, true);
      |   ^~~~~~~~~~~~~~~~~~~~
      |   i2c_ll_set_data_mode
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c: In function 'i2c_slave_set_frequency':
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c:521:3: error: implicit declaration of function 'i2c_ll_cal_bus_clk'; did you mean 'i2c_ll_enable_bus_clock'? [-Werror=implicit-function-declaration]
  521 |   i2c_ll_cal_bus_clk(XTAL_CLK_FREQ, clk_speed, &clk_cal);
      |   ^~~~~~~~~~~~~~~~~~
      |   i2c_ll_enable_bus_clock
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c:526:3: error: implicit declaration of function 'i2c_ll_set_bus_timing'; did you mean 'i2c_ll_set_scl_timing'? [-Werror=implicit-function-declaration]
  526 |   i2c_ll_set_bus_timing(i2c->dev, &clk_cal);
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   i2c_ll_set_scl_timing
E:/vstudio/esp32_example_project/arduino-as-component_bk/components/arduino/cores/esp32/esp32-hal-i2c-slave.c:527:3: error: implicit declaration of function 'i2c_ll_set_filter'; did you mean 'i2c_ll_set_tout'? [-Werror=implicit-function-declaration]
  527 |   i2c_ll_set_filter(i2c->dev, 3);
      |   ^~~~~~~~~~~~~~~~~
      |   i2c_ll_set_tout
cc1.exe: some warnings being treated as errors
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
You are not using Arduino IDE, but IDF and Arduino as component. It is not clear which version of IDF you are using and I will bet is not the correct one. Current Arduino master branch works with IDF 5.1.x (latest)

**Comment by Jason2866** [comment]
Using wrong IDF version. This is shown in log `-DIDF_VER=\"v5.3.1\` So using IDF 5.3.1 with Arduino branch master. This is wrong.
