### ISSUE TITLE
Downgrade to 1.0.1 (see #2786) gives compilation errors 

### ISSUE THREAD

**Issue by HighTML** [espressif/arduino-esp32#2877]
See https://github.com/espressif/arduino-esp32/issues/2786

PubSubClient needs EthernetClient.h and cannot compile on ESP 1.0.2
M5ez versions 2.1.0 through 2.0.0 don't compile with ESP 1.0.1

Any thoughts on getting both  PubSubClient and M5ez working?

### Hardware:
Board:							M5Stack ESP32
Computer OS:                                        Mac OSX

**Comment by HighTML** [comment]
After a lot of trial and error... Found the answer myself. I need to downgrade ESP to 1.0.1, M5ez to 2.0.1 AND M5Stack to 0.2.6
