### ISSUE TITLE
Board Manager esp32 version 3.0.0-alpha2  does not support MCPWM

### ISSUE THREAD

**Issue by Xuexi289** [espressif/arduino-esp32#8783]
### Board

ESP32 Dev Module

### Device Description

I updated esp32 by Espressif Systems from 2.0.14 to 3.0.0-alpha2 and 3.0.0-alpha1. When I compile my code, both 3.0.0 versions return with the following errors messages 

C:\Users\iv_gamer\Documents\Arduino\solar_20\pwm.ino:107:3: error: 'mcpwm_sync_enable' was not declared in this scope; did you mean 'mcpwm_sync_disable'?
  107 |   mcpwm_sync_enable(MCPWM_UNIT_1, MCPWM_TIMER_0, MCPWM_SELECT_TIMER0_SYNC, 0);

 I changed the esp32 version back to 2.0.14, there is no error.

### Hardware Configuration

Nothing connected

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE 2.1.0

### Operating System

Window 10

### Flash frequency

40MHz

### PSRAM enabled

yes

### Upload speed

11520

### Description

Codes does no compile with esp32 version 3.0.0-alpha1 or 3.0.0-alpha2

### Sketch

```cpp
#include "driver/mcpwm.h"
mcpwm_config_t pwm_1; // mcpwm config structure
#define ck_t1 32  //clk t1 pin
#define ck_s1 33  //clk s1 pin

int64_t tmM_start; // start time

void setup() {
  Serial.begin(115200);  // set up serial monitor 
  tmM_start= esp_timer_get_time();
  Serial.printf("start time =%ld \n",tmM_start);
  init_mcpwm1();
}

void loop() {


}
//********************************************************
void init_mcpwm1() {
  float duty;  // clock pulse duty cycle
  int i;
  Serial.printf(" Setting up mcpwm 1\t");
  // setup pwm 1 clock clock pins
  pinMode(ck_t1, OUTPUT);
  pinMode(ck_s1, OUTPUT);
  digitalWrite(ck_t1, LOW);  // disable convertor clock
  digitalWrite(ck_s1, LOW);  // disable convertor clock

  // ******** struct mcpwm_config_t **********
  // uint32_t frequency   MCPWM frequency in Hz
  // float cmpr_a         Duty cycle in % for operator a(MCPWMXA), for 62.3% duty cycle, duty_a = 62.3
  // float cmpr_b         Duty cycle in % for operator b(MCPWMXB), i.e for 48% duty cycle, duty_b = 48.0
  // Signal type          MCPWM_DUTY_MODE_0;  // Active high duty
  //                      MCPWM_DUTY_MODE_1;  // Active low duty
  //                      MCPWM_HAL_GENERATOR_MODE_FORCE_LOW;  // Force low
  //                      MCPWM_HAL_GENERATOR_MODE_FORCE_HIGH; // Force high
  // MCPWM counter        MCPWM_FREEZE_COUNTER;   // Counter freeze
  //                      MCPWM_UP_COUNTER;       // Up counter
  //                      MCPWM_DOWN_COUNTER;     // Down counter
  //                      MCPWM_UP_DOWN_COUNTER;  // Up-down counter, frequency is half of MCPWM frequency set
  // *****************************************************************************************

  pwm_1.frequency = 20000;                //frequency
  pwm_1.cmpr_a = 30.0;                     //duty cycle of PWMxA = 30%
  pwm_1.cmpr_b = 30.0;                     //duty cycle of PWMxB = 30%
  pwm_1.counter_mode = MCPWM_UP_COUNTER;  // Up-down counter (triangle wave)
  pwm_1.duty_mode = MCPWM_DUTY_MODE_0;    // Active HIGH

  // ******* mcpwm_gpio_init( cpwm_num, io_signals, int gpio_num) ***********
  // Setup one clock to one GPIO pin
  // For multiple GPIO pins, use multiple mcpwm_gpio_init()
  //    mcpwm_num:  [MCPWM_UNIT_0,  MCPWM_UNIT_1]
  //    io_signal:  [MCPWM0A, MCPWM0B, MCPWM1A, MCPWM1B, MCPWM2A, MCPWM2B] 1 of 6 to GPIO. Others choices [SYNC_X, FAULT_X, CAP_X]  are ignored
  //    gpio_num:   GPIO pin.
  // *****************************************************************************************

  mcpwm_gpio_init(MCPWM_UNIT_1, MCPWM0A, ck_t1);  // TIMER 0A uses as t1 clock, duty controls by pwm_1.cmpr_a
  mcpwm_gpio_init(MCPWM_UNIT_1, MCPWM1B, ck_s1);  // TIMER 1B uses as s1 clock, duty controls by pwm_1.cmpr_b

  // ******** mcpwm_init( mcpwm_num, timer_num, *mcpwm_conf) **********
  // Setup clock with the parameters defined by struct mcpwm_config_t and enable its output
  // mcpwm_num:  [MCPWM_UNIT_0,    MCPWM_UNIT_1]
  // timer_num:  [MCPWM_TIMER_0, MCPWM_TIMER_1, MCPWM_TIMER_2]
  // mcpwm_conf: Data structure address mcpwm_config_t
  // *****************************************************************************************
  mcpwm_init(MCPWM_UNIT_1, MCPWM_TIMER_0, &pwm_1);  // setup MCPWM_UNIT_1  MCPWM_TIMER_0
  mcpwm_init(MCPWM_UNIT_1, MCPWM_TIMER_1, &pwm_1);  // setup MCPWM_UNIT_1  MCPWM_TIMER_1
  // ********* mcpwm_set_timer_sync_output(mcpwm_num, timer_num, trigger_mod) ********
  // Setup MCPWM synchronization mode
  // mcpwm_num: [MCPWM_UNIT_0,    MCPWM_UNIT_1]
  // timer_num: [MCPWM_TIMER_0, MCPWM_TIMER_1, MCPWM_TIMER_2]
  // trigger_mode:
  //    MCPWM_SWSYNC_SOURCE_SYNCIN;      // Sync by external signal
  //    MCPWM_SWSYNC_SOURCE_TEZ;         // Sync when timer counts to 0
  //    MCPWM_SWSYNC_SOURCE_TEP;         // Sync when timer counts to max
  //    MCPWM_SWSYNC_SOURCE_DISABLED;    // No Sync signals
  // *****************************************************************************************
  mcpwm_set_timer_sync_output(MCPWM_UNIT_1, MCPWM_TIMER_0, MCPWM_SWSYNC_SOURCE_TEZ);

  // ************ mcpwm_sync_enable( mcpwm_num, timer_num, sync_sig, uint32_t phase_val) ************
  // Synchronized timer to the phase_val.
  // mcpwm_num: [MCPWM_UNIT_0,    MCPWM_UNIT_1]
  // timer_num:  [MCPWM_TIMER_0, MCPWM_TIMER_1, MCPWM_TIMER_2]
  // sync_sig: set the synchronization input signal
  //    MCPWM_SELECT_NO_INPUT;        // No input selected
  //    MCPWM_SELECT_TIMER0_SYNC;     // timer0 as input
  //    MCPWM_SELECT_TIMER1_SYNC;     // timer1 as input
  //    MCPWM_SELECT_TIMER2_SYNC;     // timer2 as input
  //    MCPWM_SELECT_GPIO_SYNC0;      // GPIO SYNC0 as input
  //    MCPWM_SELECT_GPIO_phas1;      // GPIO phas1 as input
  //    MCPWM_SELECT_GPIO_SYNC2;      // GPIO SYNC2 as input
  // phase_val: phase value in 10 x % (for 56.7%, phase_val = 567)
  // **********************************

  mcpwm_sync_enable(MCPWM_UNIT_1, MCPWM_TIMER_0, MCPWM_SELECT_TIMER0_SYNC, 0);
  mcpwm_sync_enable(MCPWM_UNIT_1, MCPWM_TIMER_1, MCPWM_SELECT_TIMER0_SYNC, 500);
    mcpwm_init(MCPWM_UNIT_1, MCPWM_TIMER_0, &pwm_1);
    mcpwm_init(MCPWM_UNIT_1, MCPWM_TIMER_1, &pwm_1);
  Serial.printf(" init done\n");
 }
```

### Debug Message

```plain
FQBN: esp32:esp32:esp32
Using board 'esp32' from platform in folder: C:\Users\iv_gamer\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2
Using core 'esp32' from platform in folder: C:\Users\iv_gamer\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2

cmd /c if exist "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\partitions.csv" COPY /y "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\partitions.csv" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\partitions.csv"
cmd /c if not exist "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\partitions.csv" if exist "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32\\partitions.csv" COPY "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32\\partitions.csv" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\partitions.csv"
cmd /c if not exist "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\partitions.csv" COPY "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\tools\\partitions\\default.csv" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\partitions.csv"
        1 file(s) copied.
cmd /c IF EXIST "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\bootloader.bin" ( COPY /y "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\bootloader.bin" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch_oct19c.ino.bootloader.bin" ) ELSE ( IF EXIST "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32\\bootloader.bin" ( COPY "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32\\bootloader.bin" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch_oct19c.ino.bootloader.bin" ) ELSE ( "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esptool_py\\4.6/esptool.exe" --chip esp32 elf2image --flash_mode dio --flash_freq 80m --flash_size 4MB -o "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch_oct19c.ino.bootloader.bin" "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32\\bin\\bootloader_qio_80m.elf" ) )
esptool.py v4.6
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
cmd /c if exist "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\build_opt.h" COPY /y "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c\\build_opt.h" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\build_opt.h"
cmd /c if not exist "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\build_opt.h" type nul > "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\build_opt.h"
Detecting libraries used...
"C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\esp-12.2.0_20230208/bin/xtensa-esp32-elf-g++" -c "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/cpp_flags" -w -Os -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:esp32:JTAGAdapter=default,PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,LoopCore=1,EventsCore=1,DebugLevel=none,EraseFlash=none\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_RUNNING_CORE=1 -DARDUINO_EVENT_RUNNING_CORE=1 -DARDUINO_USB_CDC_ON_BOOT=0 "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/defines" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c" -iprefix "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/include/" "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/includes" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/qio_qspi/include" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\cores\\esp32" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32" "@C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03/build_opt.h" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch\\sketch_oct19c.ino.cpp" -o nul
Generating function prototypes...
"C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\esp-12.2.0_20230208/bin/xtensa-esp32-elf-g++" -c "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/cpp_flags" -w -Os -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:esp32:JTAGAdapter=default,PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,LoopCore=1,EventsCore=1,DebugLevel=none,EraseFlash=none\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_RUNNING_CORE=1 -DARDUINO_EVENT_RUNNING_CORE=1 -DARDUINO_USB_CDC_ON_BOOT=0 "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/defines" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c" -iprefix "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/include/" "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/includes" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/qio_qspi/include" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\cores\\esp32" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32" "@C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03/build_opt.h" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch\\sketch_oct19c.ino.cpp" -o "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\builtin\\tools\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\esp-12.2.0_20230208/bin/xtensa-esp32-elf-g++" -MMD -c "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/cpp_flags" -w -Os -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:esp32:JTAGAdapter=default,PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,LoopCore=1,EventsCore=1,DebugLevel=none,EraseFlash=none\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_RUNNING_CORE=1 -DARDUINO_EVENT_RUNNING_CORE=1 -DARDUINO_USB_CDC_ON_BOOT=0 "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/defines" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\\sketch_oct19c" -iprefix "C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/include/" "@C:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/flags/includes" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-6b1f40b9bf/esp32/qio_qspi/include" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\cores\\esp32" "-IC:\\Users\\iv_gamer\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-alpha2\\variants\\esp32" "@C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03/build_opt.h" "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch\\sketch_oct19c.ino.cpp" -o "C:\\Users\\iv_gamer\\AppData\\Local\\Temp\\arduino\\sketches\\D94F4CA327BDB39B2A17282ACABB9E03\\sketch\\sketch_oct19c.ino.cpp.o"
C:\Users\iv_gamer\AppData\Local\Temp\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\sketch_oct19c\sketch_oct19c.ino: In function 'void init_mcpwm1()':
C:\Users\iv_gamer\AppData\Local\Temp\.arduinoIDE-unsaved2023919-11200-xdg972.argpk\sketch_oct19c\sketch_oct19c.ino:96:3: error: 'mcpwm_sync_enable' was not declared in this scope; did you mean 'mcpwm_sync_disable'?
   96 |   mcpwm_sync_enable(MCPWM_UNIT_1, MCPWM_TIMER_0, MCPWM_SELECT_TIMER0_SYNC, 0);
      |   ^~~~~~~~~~~~~~~~~
      |   mcpwm_sync_disable

exit status 1

Compilation error: 'mcpwm_sync_enable' was not declared in this scope; did you mean 'mcpwm_sync_disable'?
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
This is ESP-IDF API that has changed in version 5.1/ I suggest you rework your code to support the new API
