### ISSUE TITLE
3.3.8 updated - error: 'BOARD_SDMMC_POWER_CHANNEL' undeclared (first use in this function)

### ISSUE THREAD

**Issue by JoeIsAtWork** [espressif/arduino-esp32#12526]
### Board

ESP32P4 Core Board

### Device Description

CrowPanel Advanced 7inch |ESP32-P4 HMI AI Display 1024x600 IPS Touch Screen

### Hardware Configuration

Connecting to an Arduino Giga thru Serial1 with UART1_EXTRA_GPIO_RXD, UART1_EXTRA_GPIO_TXD pins.

### Version

v3.3.8

### Type

Bug

### IDE Name

Arduino IDE 2.3.8

### Operating System

Windows 10

### Flash frequency

default

### PSRAM enabled

yes

### Upload speed

921600

### Description

As for the question in this ticket submission: '_Flash frequency_' and '_PSRAM_' i do not now, what ever the defaults are, i did not change.

Using library's:
LovyanGFX 1.18
lvgl 8.3.11

UI = Squareline

Issue:
3.3.7 = was working fine
After updating to 3.3.8 can not compile, get the following error:
`C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c:299:32: error: 'BOARD_SDMMC_POWER_CHANNEL' undeclared (first use in this function)
  299 |       ldo_config.ldo_chan_id = BOARD_SDMMC_POWER_CHANNEL;`

### Sketch

```cpp
n/a
```

### Debug Message

```plain
`In file included from n:/_MyPrograms/Arduino/CrowPanel/libraries/lvgl/src/core/lv_obj.h:140,
                 from n:/_MyPrograms/Arduino/CrowPanel/libraries/lvgl/lvgl.h:35,
                 from n:\_MyPrograms\Arduino\CrowPanel\libraries\lvgl\src/lvgl.h:17,
                 from N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\gfx.h:32,
                 from N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\Roatary_Table_UI.ino:10:
n:/_MyPrograms/Arduino/CrowPanel/libraries/lvgl/src/core/lv_obj_style.h: In function 'void lv_obj_remove_style_all(_lv_obj_t*)':
n:/_MyPrograms/Arduino/CrowPanel/libraries/lvgl/src/core/lv_obj_style.h:94:48: warning: bitwise operation between different enumeration types '<unnamed enum>' and '<unnamed enum>' is deprecated [-Wdeprecated-enum-enum-conversion]
   94 |     lv_obj_remove_style(obj, NULL, LV_PART_ANY | LV_STATE_ANY);
      |                                    ~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\ui_events_calls.h:77,
                 from N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\Roatary_Table_UI.ino:51:
N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\ui_events_calls_funks.h: In function 'void CycleStart_Send(CYCLE_START_ENABLED)':
N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\ui_events_calls_funks.h:254:69: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  254 |                                 DisplayUpdate_MainScreenInfoMessage("");
      |                                                                     ^~
N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\gfx.h: At global scope:
N:\_MyPrograms\Arduino\_Mine\Rotary_Table\Roatary_Table_UI\gfx.h:78:20: warning: 'TAG' defined but not used [-Wunused-variable]
   78 | static const char *TAG = "TOUCH_APP";  // Tag for logging messages
      |                    ^~~
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c: In function 'setLDOPower':
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c:299:32: error: 'BOARD_SDMMC_POWER_CHANNEL' undeclared (first use in this function)
  299 |       ldo_config.ldo_chan_id = BOARD_SDMMC_POWER_CHANNEL;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c:299:32: note: each undeclared identifier is reported only once for each function it appears in
In file included from C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c:70:
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c: In function '_spiSetClockDivInternal':
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.8\cores\esp32\esp32-hal-spi.c:637:32: warning: passing argument 1 of 'spi_ll_set_clk_source' discards 'volatile' qualifier from pointer target type [-Wdiscarded-qualifiers]
  637 |       spi_ll_set_clk_source(spi->dev, new_clk_src ? SPI_CLK_SRC_SPLL : SPI_CLK_SRC_XTAL);
      |                             ~~~^~~~~
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\tools\esp32p4_es-libs\3.3.8/include/hal/esp32p4/include/hal/spi_ll.h:205:90: note: in definition of macro 'spi_ll_set_clk_source'
  205 | #define spi_ll_set_clk_source(...) (void)__DECLARE_RCC_ATOMIC_ENV; spi_ll_set_clk_source(__VA_ARGS__)
      |                                                                                          ^~~~~~~~~~~
C:\Users\Joe\AppData\Local\Arduino15\packages\esp32\tools\esp32p4_es-libs\3.3.8/include/hal/esp32p4/include/hal/spi_ll.h:179:53: note: expected 'spi_dev_t *' but argument is of type 'volatile spi_dev_t *'
  179 | static inline void spi_ll_set_clk_source(spi_dev_t *hw, spi_clock_source_t clk_source)
      |                                          ~~~~~~~~~~~^~
exit status 1

Compilation error: exit status 1`
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
This is missing from the [variant file](https://github.com/espressif/arduino-esp32/blob/master/variants/esp32p4_core_board/pins_arduino.h). 
This needs to be in all ESP32-P4 variants.

**Comment by lbernstone** [comment]
@me-no-dev Should [this](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-spi.c#L299) have an ifdef, or is it correct to throw an error if this is not set?

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y please take care of this as part of the power overhaul

**Comment by P-R-O-C-H-Y** [comment]
@JoeIsAtWork Hi, this issue was already fixed in 3.3.9+ so please update to newer release. PRs: https://github.com/espressif/arduino-esp32/pull/12620 and https://github.com/espressif/arduino-esp32/pull/12643

**Comment by reflectingme** [comment]
I can reproduce this on macOS with M5Stack Tab5.

Board:
M5Tab5 - M5Stack

Package:
m5stack esp32 3.3.8

Result:
Compilation fails in:
/Users/johnburns/Library/Arduino15/packages/m5stack/hardware/esp32/3.3.8/cores/esp32/esp32-hal-spi.c:299

Error:
'BOARD_SDMMC_POWER_CHANNEL' undeclared

Rollback test:
Downgrading to m5stack esp32 3.3.7 fixes the problem immediately and the same project compiles successfully.

Notes:
- This worked previously with the same project and board selection.
- The correct board is selected: M5Tab5 - M5Stack.
- This appears to be a regression in 3.3.8 rather than a sketch issue.
- The Tab5 variant file involved is:
  /Users/johnburns/Library/Arduino15/packages/m5stack/hardware/esp32/3.3.8/variants/m5stack_tab5/pins_arduino.h
