### ISSUE TITLE
Compile error after upgrade to 2.0.0 WebAuthentication.cpp:73: undefined reference to `mbedtls_md5_starts

### ISSUE THREAD

**Issue by mpbejo** [espressif/arduino-esp32#5700]
Hi everybody,
I just upgrade from 1.0.6 to 2.0.0 and now I have this error:

WebAuthentication.cpp:73: undefined reference to `mbedtls_md5_starts'

I found this, that could be useful
https://github.com/me-no-dev/ESPAsyncWebServer/pull/970
but, sorry I do not understand what to do

Could You help me?
Thank You
Best Regards
Marco

**Comment by atanisoft** [comment]
@mpbejo This has been fixed in the ESPAsyncWebServer master code, you will need to refresh your copy of the library to the latest version from GitHub.

**Comment by mpbejo** [comment]
@atanisoft thank You very much for the tip!
Best Regards
