### PR TITLE
ESP-IDF v5.1

### PR DESCRIPTION
**Pull request by me-no-dev**
### Changes that need to be done:

- [ ] Replace all FreeRTOS handles to [the new API](https://github.com/espressif/arduino-esp32/blob/esp-idf-v5.1-libs/tools/sdk/esp32/include/freertos/FreeRTOS-Kernel/include/freertos/FreeRTOS.h#L1045-L1077) to allow running as component when compatibility is disabled
- [x] Refactor `platform.txt` to not use components installed through the board manager when running from git
- [x] Create Peripheral Manager to keep track of bus drivers and pins

#### ESP-IDF Driver Deprecations

- [x] ADC

```
In file included from cores/esp32/esp32-hal-adc.c:16:
tools/sdk/esp32/include/driver/deprecated/driver/adc.h:19
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~

In file included from cores/esp32/esp32-hal-adc.c:17:
tools/sdk/esp32/include/esp_adc/deprecated/include/esp_adc_cal.h:17
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
```

- [x] DAC

```
In file included from cores/esp32/esp32-hal-dac.c:22:
tools/sdk/esp32/include/driver/deprecated/driver/dac.h:16
   16 | #warning "The legacy DAC driver is deprecated, please use `driver/dac_oneshot.h`, `driver/dac_cosine.h` or `driver/dac_continuous.h` instead"
      |  ^~~~~~~
```

- [x] RMT

```
In file included from cores/esp32/esp32-hal-rmt.c:16:
tools/sdk/esp32/include/driver/deprecated/driver/rmt.h:18
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
```

- [x] Sigma Delta

```
In file included from cores/esp32/esp32-hal-sigmadelta.c:19:
tools/sdk/esp32/include/driver/deprecated/driver/sigmadelta.h:15
   15 | #warning "The legacy sigma-delta driver is deprecated, please use driver/sdm.h"
      |  ^~~~~~~
```

- [x] HW Timer

```
In file included from cores/esp32/esp32-hal-timer.c:16:
tools/sdk/esp32/include/driver/deprecated/driver/timer.h:16
   16 | #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h"
      |  ^~~~~~~
```

- [ ] I2S

```
In file included from tools/sdk/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from libraries/I2S/src/I2S.h:26:
tools/sdk/esp32/include/driver/deprecated/driver/adc.h:19
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~

In file included from libraries/I2S/src/I2S.h:26:
tools/sdk/esp32/include/driver/deprecated/driver/i2s.h:27
   27 | #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead.
      |  ^~~~~~~

libraries/I2S/src/I2S.cpp:148
  148 |     #warning The following values are new and need to be checked
      |      ^~~~~~~
```

- [ ] I2S Example

```
In file included from tools/sdk/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from libraries/ESP32/examples/I2S/HiFreq_ADC/HiFreq_ADC.ino:23:
tools/sdk/esp32/include/driver/deprecated/driver/adc.h:19
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~

In file included from libraries/ESP32/examples/I2S/HiFreq_ADC/HiFreq_ADC.ino:23:
tools/sdk/esp32/include/driver/deprecated/driver/i2s.h:27
   27 | #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead.
      |  ^~~~~~~
```

##### Insights

```
In file included from tools/sdk/esp32/include/esp_insights/include/esp_insights.h:18,
                 from libraries/Insights/src/Insights.cpp:8:
tools/sdk/esp32/include/esp_diagnostics/include/esp_diagnostics.h:241:29: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
  241 |     esp_diag_log_event(tag, "EV (%"PRIu32") %s: " format, esp_log_timestamp(), tag, ##__VA_ARGS__); \
      |      
```

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
**To-Do list till Wednesday 25.1.:**
- @SuGlider & @P-R-O-C-H-Y - please check related drivers and think about possible approach for porting them
-- @P-R-O-C-H-Y can handle ADC, DAC, SigmaDelta and Timer
-- @SuGlider can handle RMT and I2S
- @PilnyTomas - please check out this branch and update new toolchain and test WiFI & Bluetooth (run some examples)

**Comment by SuGlider** [comment]
### RMT Report
All the Arduino ESP32 RMT examples compiled and worked as expected using ESP32 and ESP32C3 (using IDF 5.1 Legacy Driver)

New IDF 5.1 RMT is quite different when compared with IDF 4.4 (which has the same API as the IDF 5.1 Legacy Driver)
Refactoring RMT to use new API from IDF 5.1 will demand some effort and time.

**Comment by P-R-O-C-H-Y** [comment]
Report from peripherals testing:

**ADC:**
- Found BUG analogRead -> line 178 (return) is wrong, should be 0 because error occured (not related to IDF 5.x)
- ADC not working on all chips using IDF 5.1 legacy driver
- New ADC driver, split ADC source files to Continuous / OneShot, refactoring needed.
- side note for migration guide - Hall sensor read REMOVED from IDF 5.X (Hristo removed that already)

**DAC:**
- DAC tested using IDF 5.1 legacy driver, working on ESP32 but broken on ESP32-S2
- new DAC driver have been redesigned, need to be refactored.

**Sigma-Delta:**
- Example compiled and working using IDF 5.1 legacy driver
- Tested on ESP32, ESP32-C3, ESP32-S2 and ESP32-S3
- New SigmaDelta driver have new API, refactoring is needed (not that complicated)

**Timer:**
- HW test compiled and working using IDF 5.1 legacy driver
- Tested on ESP32, pytest seems to not work properly, compiling working on all chips, but running test doesn’t accept other chips than ESP32
- New Timer driver (GPTimer) have new API, refactoring is needed
- New driver seems to be allowed to run within ISR context (should fix some related issues)

**Comment by PilnyTomas** [comment]
WiFi examples have this error:
```
esp32/libraries/WiFi/src/WiFiGeneric.h:33:10: fatal error: esp_eth_driver.h: No such file or directory
   33 | #include "esp_eth_driver.h"
```

BT examples show this error:
```
esp32/cores/esp32/Esp.h:115:22: error: 'esp_cpu_get_cycle_count' was not declared in this scope; did you mean 'esp_cpu_get_ccount'?
  115 |     return (uint32_t)esp_cpu_get_cycle_count();
```

Also, BT displays some warnings:
```
esp32/tools/sdk/esp32/include/freertos/port/xtensa/include/freertos/portmacro.h:613:48: warning: ignoring attribute 'section (".iram1.24")' because it conflicts with previous 'section (".iram1.22")' [-Wattributes]
  613 | static inline bool IRAM_ATTR xPortCanYield(void)

esp32/tools/sdk/esp32/include/freertos/port/xtensa/include/freertos/portmacro.h:343:30: note: previous declaration here
  343 | static inline bool IRAM_ATTR xPortCanYield(void);

esp32/tools/sdk/esp32/include/freertos/port/xtensa/include/freertos/portmacro.h:632:55: warning: ignoring attribute 'section (".iram1.25")' because it conflicts with previous 'section (".iram1.23")' [-Wattributes]
  632 | static inline BaseType_t IRAM_ATTR xPortGetCoreID(void)

esp32/tools/sdk/esp32/include/freertos/port/xtensa/include/freertos/portmacro.h:385:36: note: previous declaration here
  385 | static inline BaseType_t IRAM_ATTR xPortGetCoreID(void);
```

**Comment by PilnyTomas** [comment]
Branch `esp-idf-v5.1-libs` SoC `ESP32
WiFi examples:
- [ ] FTM
- [ ] SimpleWiFiServer
- [ ] WiFiAccessPoint
- [ ] WiFiBlueToothSwitch
- [ ] WiFiClient
- [ ] WiFiClientBasic
- [ ] WiFiClientConnect
- [ ] WiFiClientEnterprise
- [ ] WiFiClientEvents
- [ ] WiFiClientStaticIP
- [ ] WiFiIPv6
- [ ] WiFiMulti
- [ ] WiFiScan
- [ ] WiFiScanDualAntenna
- [ ] WiFiSmartConfig
- [ ] WiFiTelnetToSerial
- [ ] WiFiUDPClient
- [ ] WPS

**Comment by SuGlider** [comment]
> ### RMT Report
> All the Arduino ESP32 RMT examples compiled and worked as expected using ESP32 and ESP32C3 (using IDF 5.1 Legacy Driver)
> 
> New IDF 5.1 RMT is quite different when compared with IDF 4.4 (which has the same API as the IDF 5.1 Legacy Driver) Refactoring RMT to use new API from IDF 5.1 will demand some effort and time.

IDF 5.1 RMT Legacy Driver confirmed working correctly for ESP32, ESP32S2, ESP32S3 and ESP32C3, the sameway it works with Arduino Core 2.0.6.

**Comment by P-R-O-C-H-Y** [comment]
@SuGlider for the I2S testing, you can maybe ask @PilnyTomas for the pytest sketch if it's done.

**Comment by SuGlider** [comment]
> @SuGlider for the I2S testing, you can maybe ask @PilnyTomas for the pytest sketch if it's done.

I'm using the basic examples for testing I2S  with a logic analyzer.

@PilnyTomas - Do you have a pytest script for testing I2S? 
Please send me also some instructions, given that the PC has no I2S interface.

**Comment by SuGlider** [comment]
### I2S Report
Arduino ESP32 I2S examples SimpleTone and ADCPlotter compiled and worked as expected using ESP32 (using IDF 5.1 Legacy Driver). I couldn't teste correctly the examples InputSerialPlotter and FullDuplex, although, both seem to work.

When uploaded any example to ESP32-S2, the board reboots. The same for Arduino Core 2.0.6, thus I consider that no change can be noticed.
For S3, the examples fail with an I2S initialization error, which seems related to default GPIO setup. 
Again it also happens with the 2.0.6, thus I also consider that IDF 4.4 and IDF 5.1 are working in the same way.

New IDF 5.1 I2S is totally different when compared with IDF 4.4 (which has the same API as the IDF 5.1 Legacy Driver)
It seems clear that IDF 5.1 doesn't support the "driver" mode, therefore, it may require a new way of implementing the I2S library.

**Comment by VojtechBartoska** [comment]
Linking Migration Guide for IDF: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/index.html

Except those peripherals mentioned above, some other will need to be updated.

**Comment by SuGlider** [comment]
> Linking Migration Guide for IDF: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/index.html
> 
> Except those peripherals mentioned above, some other will need to be updated.

We didn't test yet Libraries such as BT, BLE, ETH, SPI, I2C, USB, SDCard, File Systems, OTA, Rainmaker, Insights, DNS, etc.
It may take some time to check  all ot it. 
Even more time to refactor all to the new IDF 5.1 APIs, leaving away the deprecated legacy drivers.

**Comment by lboue** [comment]
[ESP-IDF Release v5.1](https://github.com/espressif/esp-idf/releases/tag/v5.1) has been released.

**Comment by me-no-dev** [comment]
> Hi! I’m really looking forward to this new version of arduino-esp32! Is there any indication on when we can start trying it?

you can start now if you install it through github. Just make sure you pull the correct branch and then execute `tools/get.exe` or `tools/get.py`
