### ISSUE TITLE
index not declared in this scope after upgrade to v3 from v2

### ISSUE THREAD

**Issue by chemistorge** [espressif/arduino-esp32#10560]
### Board

DOIT ESP32 DEVKIT V1

### Device Description

.arduino15/packages/esp32/hardware/esp32/3.0.3/libraries/WebServer/src/WebServer.cpp: In member function 'bool WebServer::authenticate(THandlerFunctionAuthCheck)':
.arduino15/packages/esp32/hardware/esp32/3.0.3/libraries/WebServer/src/WebServer.cpp:170:83: error: 'index' was not declared in this scope
  170 |       if (base64_decode_chars(authReq.c_str(), authReq.length(), decoded) && (p = index(decoded, ':')) && p) {

### Hardware Configuration

//

### Version

v3.0.3

### IDE Name

Arduino IDE

### Operating System

Linux

### Flash frequency

//

### PSRAM enabled

yes

### Upload speed

115200

### Description

index not declared in webserver.cpp

### Sketch

```cpp
//
```

### Debug Message

```plain
.arduino15/packages/esp32/hardware/esp32/3.0.3/libraries/WebServer/src/WebServer.cpp: In member function 'bool WebServer::authenticate(THandlerFunctionAuthCheck)':
.arduino15/packages/esp32/hardware/esp32/3.0.3/libraries/WebServer/src/WebServer.cpp:170:83: error: 'index' was not declared in this scope
  170 |       if (base64_decode_chars(authReq.c_str(), authReq.length(), decoded) && (p = index(decoded, ':')) && p) {
```

### Other Steps to Reproduce

Works fine in v2

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.
