### ISSUE TITLE
ArduinoBLE fails to build on H2 and C6 using v3.3.0 release

### ISSUE THREAD

**Issue by pennam** [espressif/arduino-esp32#11716]
### Board

ESP32H2 Dev Module, ESP32C6 Dev Module

### Device Description

ESP32H2 Dev Module, ESP32C6 Dev Module

### Hardware Configuration

Nothing connected to the board

### Version

v3.3.0

### Type

Bug

### IDE Name

Arduino IDE

### Operating System

linux

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

ArduinoBLE fails to [build](https://github.com/arduino-libraries/ArduinoBLE/actions/runs/16491446171/job/46626851548) reporting undefined reference error on ESP32C6 Dev module and ESP32H2 Dev Module using release v3.3.0

```
Linking everything together...
/home/pennam/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/riscv32-esp-elf-g++ -Wl,--Map=/home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/LED.ino.map -L/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/lib -L/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/ld -L/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/qio_qspi -Wl,--wrap=esp_panic_handler @/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/flags/ld_flags @/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/flags/ld_scripts -Wl,--start-group /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/sketch/LED.ino.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLEAdvertisingData.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLECharacteristic.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLEDescriptor.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLEDevice.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLEService.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLEStringCharacteristic.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/BLETypedCharacteristics.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/local/BLELocalAttribute.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/local/BLELocalCharacteristic.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/local/BLELocalDescriptor.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/local/BLELocalDevice.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/local/BLELocalService.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/remote/BLERemoteAttribute.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/remote/BLERemoteCharacteristic.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/remote/BLERemoteDescriptor.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/remote/BLERemoteDevice.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/remote/BLERemoteService.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/ATT.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/BLEUuid.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/GAP.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/GATT.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCI.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCICordioTransport.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCISilabsTransport.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCIUartTransport.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCIVirtualTransport.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCIVirtualTransportAT.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCIVirtualTransportZephyr.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/L2CAPSignaling.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/bitDescriptions.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/btct.cpp.o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/keyDistribution.cpp.o /home/pennam/.cache/arduino/cores/863c5312e7d031f425617a00ff296d89/core.a @/home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/flags/ld_libs -Wl,--end-group -Wl,-EL -o /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/LED.ino.elf
/home/pennam/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/pennam/.cache/arduino/sketches/FD672518BC5C4658A71C194002B0803F/libraries/ArduinoBLE/utility/HCIVirtualTransport.cpp.o: in function `bleTask(void*)':
/home/pennam/Arduino/libraries/ArduinoBLE/src/utility/HCIVirtualTransport.cpp:51:(.text._Z7bleTaskPv+0x24): undefined reference to `esp_vhci_host_register_callback'
/home/pennam/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/pennam/Arduino/libraries/ArduinoBLE/src/utility/HCIVirtualTransport.cpp:51:(.text._Z7bleTaskPv+0x42): undefined reference to `esp_vhci_host_check_send_available'
/home/pennam/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/pennam/Arduino/libraries/ArduinoBLE/src/utility/HCIVirtualTransport.cpp:53:(.text._Z7bleTaskPv+0x54): undefined reference to `esp_vhci_host_send_packet'
collect2: error: ld returned 1 exit status
```

Functions are declared in [esp_bt.h](https://github.com/espressif/esp-idf/blob/b66b5448e0dfac6be135e6f0ac21010aba231180/components/bt/include/esp32h2/include/esp_bt.h#L372) file but not included in the build. Examples build fine using release v3.2.0

### Sketch

```cpp
https://github.com/arduino-libraries/ArduinoBLE/blob/master/examples/Peripheral/LED/LED.ino
```

### Debug Message

```plain
Cant provide because is a build error
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Arduino 3.3.0 uses NimBLE underneath, while previous versions use BlueDroid. Either use older version or move to using the BLE library included in Arduino

**Comment by pennam** [comment]
@me-no-dev  Is NimBLE enabled only for `C6` and `H2` ? other boards like `S3` and `C3` are still building fine.

**Comment by pennam** [comment]
looks like that even using NimBLE `esp_vhci_*` functions are available for `C3` and `S3`

```
nm /home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c3/lib/libbt.a | grep -e esp_vhci -e nimble
...
nimble_port.c.obj:
00000000 T esp_nimble_deinit
         U esp_nimble_hci_deinit
         U esp_nimble_hci_init
00000000 T esp_nimble_init
00000000 T nimble_port_deinit
00000000 T nimble_port_get_dflt_eventq
00000000 T nimble_port_init
00000000 T nimble_port_run
00000000 T nimble_port_stop
00000000 t nimble_port_stop_cb
nimble_port_freertos.c.obj:
00000000 T esp_nimble_disable
00000000 T esp_nimble_enable
00000000 T nimble_port_freertos_deinit
00000000 T nimble_port_freertos_init
esp_nimble_hci.c.obj:
00000000 T esp_nimble_hci_deinit
00000000 T esp_nimble_hci_init
         U esp_vhci_host_check_send_available
         U esp_vhci_host_register_callback
         U esp_vhci_host_send_packet
00000000 T esp_vhci_host_send_packet_wrapper
```

but not for `C6` and `H2`

```
nm /home/pennam/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c6/lib/libbt.a | grep -e esp_vhci -e nimble
...
nm: ble_eatt.c.obj: nessun simbolo
nimble_port.c.obj:
00000000 T esp_nimble_deinit
00000000 T esp_nimble_init
00000000 T nimble_port_deinit
00000000 T nimble_port_get_dflt_eventq
00000000 T nimble_port_init
00000000 T nimble_port_run
00000000 T nimble_port_stop
00000000 t nimble_port_stop_cb
nimble_port_freertos.c.obj:
00000000 T esp_nimble_disable
00000000 T esp_nimble_enable
00000000 T nimble_port_freertos_deinit
00000000 T nimble_port_freertos_init
```

**Comment by lucasssvaz** [comment]
There is apparently a [new HCI layer](https://github.com/espressif/esp-idf/commit/6c097b58129935ca476bd268253988ce4c8f0aa9) for C2, C5, C6 and H2.

```
commit 113c8923da6bde580c31780ab9dfd46b22ca5d8e
Author: zwl <zhaoweiliang@espressif.com>
Date:   Thu Jul 4 21:15:18 2024 +0800

    feat(bluetooth/controller): adopting new HCI layer code on ESP32-C5

commit e154fa0af2d9cee814062d804b2d72f783300899
Author: zwl <zhaoweiliang@espressif.com>
Date:   Thu Jul 4 21:14:14 2024 +0800

    feat(bluetooth/controller): adopting new HCI layer code and support UHCI function on ESP32-C6 and ESP32-H2

commit 8504040869e2235deaee9c3fb61108d1757f7c47
Author: zwl <zhaoweiliang@espressif.com>
Date:   Thu Jul 4 21:12:38 2024 +0800

    feat(bluetooth/controller): adopting new HCI layer code on ESP32-C2

commit 6c097b58129935ca476bd268253988ce4c8f0aa9
Author: zwl <zhaoweiliang@espressif.com>
Date:   Thu Jul 4 21:11:23 2024 +0800

    feat(bluetooth/controller): optimize bt hci layer code
```

These functions used by the ArduinoBLE library were deleted when adopting this new layer. The library will probably need to be adapted for this.
