### PR TITLE
change(idf): Rename component example and fix compilation warnings

### LINKED ISSUE #9607: Can't compile with CONFIG_COMPILER_OPTIMIZATION_PERF (-O2) option, ESP-IDF with arduino as a component
### Board

ESP32-WROOM-32

### Device Description

ESP32-2432S028 (Cheap Yellow Display)

### Hardware Configuration

No

### Version

latest development Release Candidate (RC-X)

### IDE Name

ESP-IDF Extension for Visual Studio Code

### Operating System

Windows 10

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

460800

### Description

Can't compile for performance. Not sure if this is the right place because the issues are with the the components this component uses. You can see a pull request to fix one of these issues here:

https://github.com/espressif/esp-rainmaker/pull/297

I manually made the same changes to fix this issue and another component broke with a reference to a potentially uninitialized enum variable. I fixed that and more strncpy errors popped up, at which point I gave up.

### Sketch

```cpp
In sdkconfig.defaults:

CONFIG_COMPILER_OPTIMIZATION_DEFAULT=n
CONFIG_COMPILER_OPTIMIZATION_SIZE=n
CONFIG_COMPILER_OPTIMIZATION_PERF=y
```

### Debug Message

```plain
/managed_components/espressif__esp_rainmaker/src/core/esp_rmaker_schedule.c:635:17: error: 'strncpy' output truncated before terminating nul copying
as many bytes from a string as its length [-Werror=stringop-truncation]
  635 |                 strncpy(*info, _info, strlen(_info));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### LINKED ISSUE #9784: Compilation error: v3.0.1 when used as esp-idf component
### Board

sparkfun esp32 thing

### Device Description

sparkfun esp32 thing

### Hardware Configuration

N/A

### Version

v3.0.1

### IDE Name

idf-idf.py command line

### Operating System

Linux

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

compilation error when using Arduino Core v3.0.1 + ESP-IDF 5.1.4.
Arduino Core is used as component.

I just run "idf.py build" and fails to compile both in:

- components/arduino/cores/esp32/esp32-hal-adc.c
- components/arduino/cores/esp32/MacAddress.cpp

It used to compile Ok using Arduino Core v2.0.17 + ESP-IDF 4.4.7

### Sketch

```cpp
Not applicable.
```

### Debug Message

```plain
* esp32-hal-adc.c


/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/esp32-hal-adc.c: In function 'analogContinuous':
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/esp32-hal-adc.c:478:27: error: 'adc_unit' may be used uninitialized [-Werror=maybe-uninitialized]
  478 |   if (adc_handle[adc_unit].adc_oneshot_handle != NULL) {
      |       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/esp32-hal-adc.c:461:14: note: 'adc_unit' declared here
  461 |   adc_unit_t adc_unit;
      |              ^~~~~~~~
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
```

* MacAddress.cpp

```
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/MacAddress.cpp: In member function 'bool MacAddress::fromString6(const char*)':
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/MacAddress.cpp:75:10: error: 'char* strncpy(char*, const char*, size_t)' specified bound 18 equals destination size [-Werror=stringop-truncation]
   75 |   strncpy(cs, buf, sizeof(cs));  //strtok modifies the buffer: copy to working buffer.
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/MacAddress.cpp: In member function 'bool MacAddress::fromString8(const char*)':
/home/riq/progs/esp-idf-arduino-bluepad32-template/components/arduino/cores/esp32/MacAddress.cpp:94:10: error: 'char* strncpy(char*, const char*, size_t)' specified bound 24 equals destination size [-Werror=stringop-truncation]
   94 |   strncpy(cs, buf, sizeof(cs));  //strtok modifies the buffer: copy to working buffer.
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```
```


### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change
Fixes component compilation and workflow conflicts.
This will also fix the workflows being canceled randomly in PRs.

## Tests scenarios
Locally and CI

## Related links
Closes #9607
Closes #9784

### CODE REVIEW

**Review by SuGlider — APPROVED** [review]
LGTM
