### ISSUE TITLE
esp32 3.0.0 Compilation error from esp_now.h with function call esp_now_register_recv_cb

### ISSUE THREAD

**Issue by rhit-jaegerba** [espressif/arduino-esp32#9737]
### Board

ESP32C3 Dev Module

### Device Description

Basic ESP32-C3-DevKit
https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitm-1.html

### Hardware Configuration

No other Hardware Attached

### Version

v3.0.0

### IDE Name

Arduino IDE 2.3.2

### Operating System

Windows 10

### Flash frequency

80 MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

Using This Example https://randomnerdtutorials.com/esp-now-esp32-arduino-ide/ For receiving and transmitting via ESPNow
The ESP32 Receiver Sketch (ESP-NOW) no longer compiles after the update to 3.0.0 due to issues within esp_now.h, verified that the sketch compiles correctly on version 2.0.17.

### Sketch

```cpp
/*
  Rui Santos
  Complete project details at https://RandomNerdTutorials.com/esp-now-esp32-arduino-ide/
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files.
  
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
*/

#include <esp_now.h>
#include <WiFi.h>

// Structure example to receive data
// Must match the sender structure
typedef struct struct_message {
    char a[32];
    int b;
    float c;
    bool d;
} struct_message;

// Create a struct_message called myData
struct_message myData;

// callback function that will be executed when data is received
void OnDataRecv(const uint8_t * mac, const uint8_t *incomingData, int len) {
  memcpy(&myData, incomingData, sizeof(myData));
  Serial.print("Bytes received: ");
  Serial.println(len);
  Serial.print("Char: ");
  Serial.println(myData.a);
  Serial.print("Int: ");
  Serial.println(myData.b);
  Serial.print("Float: ");
  Serial.println(myData.c);
  Serial.print("Bool: ");
  Serial.println(myData.d);
  Serial.println();
}
 
void setup() {
  // Initialize Serial Monitor
  Serial.begin(115200);
  
  // Set device as a Wi-Fi Station
  WiFi.mode(WIFI_STA);

  // Init ESP-NOW
  if (esp_now_init() != ESP_OK) {
    Serial.println("Error initializing ESP-NOW");
    return;
  }
  
  // Once ESPNow is successfully Init, we will register for recv CB to
  // get recv packer info
  esp_now_register_recv_cb(OnDataRecv);
}
 
void loop() {

}
```

### Debug Message

```plain
C:\Users\jaegerba\AppData\Local\Temp\.arduinoIDE-unsaved2024431-9968-ilie0.szczid\sketch_may31b\sketch_may31b.ino: In function 'void setup()':
C:\Users\jaegerba\AppData\Local\Temp\.arduinoIDE-unsaved2024431-9968-ilie0.szczid\sketch_may31b\sketch_may31b.ino:58:28: error: invalid conversion from 'void (*)(const uint8_t*, const uint8_t*, int)' {aka 'void (*)(const unsigned char*, const unsigned char*, int)'} to 'esp_now_recv_cb_t' {aka 'void (*)(const esp_now_recv_info*, const unsigned char*, int)'} [-fpermissive]
   58 |   esp_now_register_recv_cb(OnDataRecv);
      |                            ^~~~~~~~~~
      |                            |
      |                            void (*)(const uint8_t*, const uint8_t*, int) {aka void (*)(const unsigned char*, const unsigned char*, int)}
In file included from C:\Users\jaegerba\AppData\Local\Temp\.arduinoIDE-unsaved2024431-9968-ilie0.szczid\sketch_may31b\sketch_may31b.ino:12:
C:\Users\jaegerba\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-442a798083/esp32c3/include/esp_wifi/include/esp_now.h:157:54: note:   initializing argument 1 of 'esp_err_t esp_now_register_recv_cb(esp_now_recv_cb_t)'
  157 | esp_err_t esp_now_register_recv_cb(esp_now_recv_cb_t cb);
      |                                    ~~~~~~~~~~~~~~~~~~^~

exit status 1

Compilation error: invalid conversion from 'void (*)(const uint8_t*, const uint8_t*, int)' {aka 'void (*)(const unsigned char*, const unsigned char*, int)'} to 'esp_now_recv_cb_t' {aka 'void (*)(const esp_now_recv_info*, const unsigned char*, int)'} [-fpermissive]
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lucasssvaz** [comment]
Please use the new ESP NOW library and examples included in 3.0.0

**Comment by schwabe58** [comment]
Is the new library downward compatible to recent version, a.e. 2.0.17? My answer after a very first view: No
So I have to change existing code, isn't it?
Please provide a workaround for this case.

**Comment by me-no-dev** [comment]
You need to change code anyway. You were using ESP-IDF APIs before and you either have to update to the new ESP-IDF APIs or use our library from now on.

**Comment by Chenmo0414** [comment]
`void OnDataRecv(const uint8_t * mac, const uint8_t *incomingData, int len)`
Change to
`void OnDataRecv(const unsigned char* mac, constunsigned char* incomingData, int len)`
or downgrade the version

**Comment by VojtechBartoska** [comment]
Hello @rhit-jaegerba, can I consider this ticket as answered?

**Comment by ator1811** [comment]
YepRegardsVerstuurd vanaf mijn iPhoneOp 16 sep 2024 om 13:45 heeft Vojtěch Bartoška ***@***.***> het volgende geschreven:﻿
Hello @rhit-jaegerba, can I consider this ticket as answered?

**Comment by Viperzee** [comment]
> `void OnDataRecv(const uint8_t *mac, const uint8_t *incomingData, int len)` Change to `void OnDataRecv(const esp_now_recv_info_t *info, const uint8_t *incomingData, int len)` or downgrade the version

This fixed my same issue. I verified the code and it works!!! I have IDE 2.3.3. Thanks

**Comment by yonagy82** [comment]
Hello, friends,
Well, unfortunately it still doesn't work for me: I'm using Aarduino IDE Version 2.3.5, board = XIAO_ESP32C3. The library is ESP-NOW version 3.1.3. The ESP_NOW sub library is Unicast transmission by Lucas Saavedra Vaz - 2024, downloaded from https://github.com/espressif/arduino-esp32/.
I tried several bariants and went over questions and examples I've found in the net. The error message is consistent' with small variants. For instance:
1. For `esp_now_register_recv_cb(OnDataRecv)` the error is `invalid use of non-static member function 'void espNowServerClass::OnDataRecv(const uint8_t*, const uint8_t*, int)'`
2. For `esp_now_register_recv_cb(esp_now_recv_cb_t(OnDataRecv))` the error messsage is
` invalid use of member function  'void espNowServerClass::OnDataRecv(const uint8_t*, const uint8_t*, int)' (did you forget the '()'?)
`
I'm already on this for quite some time; should I downgrade the library? How to do it?

Best regards
Yona

**Comment by lukaszwitkowski** [comment]
> `void OnDataRecv(const uint8_t *mac, const uint8_t *incomingData, int len)` Change to `void OnDataRecv(const esp_now_recv_info_t *info, const uint8_t *incomingData, int len)` or downgrade the version

i do that in reciver and work ok. 
but what I need to change in my master?
my Arduino code:


// Transmitter (Tx) Code
// 18-Channel Independent Wireless Remote Switch ESP32 - ESPNow
// Code by RBMK-5000 (c) 2023

#include <esp_now.h>
#include <WiFi.h>

// REPLACE WITH YOUR RECEIVER MAC Address
uint8_t receiverMacAddress[] = {0xB8,0xD6,0x1A,0x5B,0x8E,0xDC};  // MAC ESP32 CH340 B8:D6:1A:5B:8E:DC
// B8:D6:1A:5B:8E:DC
struct PacketData
{
  byte switch1;
  byte switch2;
  byte switch3;
  byte switch4;  
  byte switch5;
  byte switch6;
  byte switch7;
  byte switch8; 
  byte switch9;
  byte switch10;
  byte switch11;
  byte switch12;
  byte switch13;
  byte switch14;
  byte switch15;
  byte switch16;
  byte switch17; 
  byte switch18;   
};
PacketData data;


// Callback Function when data sent
void OnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status) {
  Serial.print("\r\nLast Packet Send Status:\t ");
  Serial.println(status);
  Serial.println(status == ESP_NOW_SEND_SUCCESS ? "Message sent" : "Message failed");
}

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);

  // Initializing ESP_Now
  if (esp_now_init() != ESP_OK) 
  {
    Serial.println("Error initializing ESP-NOW");
    return;
  }
  else
  {
    Serial.println("Success Initializing ESP-NOW");
  }

  esp_now_register_send_cb(OnDataSent);
  
  // Registering & Adding Peer ESP
  esp_now_peer_info_t peerInfo;
  memcpy(peerInfo.peer_addr, receiverMacAddress, 6);
  peerInfo.channel = 0;  
  peerInfo.encrypt = false;
          
  if (esp_now_add_peer(&peerInfo) != ESP_OK)
  {
    Serial.println("Failed Adding Peer");
    return;
  }
  else
  {
    Serial.println("Success Adding Peer");
  } 

  pinMode(12,INPUT_PULLUP);
  pinMode(4,INPUT_PULLUP);
  pinMode(5,INPUT_PULLUP);
  pinMode(13,INPUT_PULLUP);
  pinMode(14,INPUT_PULLUP); 
  pinMode(15,INPUT_PULLUP);
  pinMode(16,INPUT_PULLUP);
  pinMode(17,INPUT_PULLUP);
  pinMode(18,INPUT_PULLUP); 
  pinMode(19,INPUT_PULLUP);
  pinMode(21,INPUT_PULLUP);
  pinMode(22,INPUT_PULLUP);
  pinMode(23,INPUT_PULLUP); 
  pinMode(25,INPUT_PULLUP);
  pinMode(26,INPUT_PULLUP);
  pinMode(27,INPUT_PULLUP);
  pinMode(32,INPUT_PULLUP); 
  pinMode(33,INPUT_PULLUP);   
}
 
void loop() {
  data.switch1   = !digitalRead(12);
  data.switch2   = !digitalRead(4);
  data.switch3   = !digitalRead(5);
  data.switch4   = !digitalRead(13);
  data.switch5   = !digitalRead(14);
  data.switch6   = !digitalRead(15);
  data.switch7   = !digitalRead(16);
  data.switch8   = !digitalRead(17);
  data.switch9   = !digitalRead(18);
  data.switch10  = !digitalRead(19);
  data.switch11  = !digitalRead(21);
  data.switch12  = !digitalRead(22);
  data.switch13  = !digitalRead(23);
  data.switch14  = !digitalRead(25);
  data.switch15  = !digitalRead(26);
  data.switch16  = !digitalRead(27); 
  data.switch17  = !digitalRead(32);
  data.switch18  = !digitalRead(33); 
  
  esp_err_t result = esp_now_send(receiverMacAddress, (uint8_t *) &data, sizeof(data));
  if (result == ESP_OK) 
  {
    Serial.println("Sending Data Success");
  }
  else 
  {
    Serial.println("Sending Data Error");
  }    
  
  delay(50);
}
