### ISSUE TITLE
Cannot compile arduino esp32-s3 project with thorvg any more

### ISSUE THREAD

**Issue by SergePD** [espressif/arduino-esp32#12276]
### Board

esp32-s3 dev module

### Device Description

esp32-s3 with SPI st7796

### Hardware Configuration

LCD

### Version

v3.3.6

### Type

Bug

### IDE Name

Arduino IDE 2.3.7

### Operating System

Windows 11

### Flash frequency

80

### PSRAM enabled

yes

### Upload speed

921600

### Description

Arduino project with thorvg works fine with v3.3.4 and earlier but gives compilation error with v3.3.5 or v3.3.6

Compilation error: exit status 1

  +++ |+#include <cstring> - do not work!

### Sketch

```cpp
any scetch with:

#include "lvgl.h" (v9.4)

and in lvgl use thorvg to render .svg files
```

### Debug Message

```plain
c:\Users\user\Documents\Arduino\controller\libraries\lvgl\src\libs\thorvg\tvgSwCommon.h:271:9: error: 'memcpy' was not declared in this scope
  271 |         memcpy(alphas, rhs->alphas, sizeof(alphas));
      |         ^~~~~~
c:\Users\user\Documents\Arduino\controller\libraries\lvgl\src\libs\thorvg\tvgSwCommon.h:32:1: note: 'memcpy' is defined in header '<cstring>'; this is probably fixable by adding '#include <cstring>'
   31 | #include "tvgRender.h"
  +++ |+#include <cstring>
```

### Other Steps to Reproduce

Works fine in v3.3.4 and earlier

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment]
What is thorvg?

**Comment by SergePD** [comment]
> What is thorvg?
Vector graphic library included in LVGL
