### ISSUE TITLE
3.3.9 / 3.3.10 error in arduino -> xtensa-esp32s3-elf-g++.exe: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by gavron04** [espressif/arduino-esp32#12681]
### Board

ESP32S3 Dev module

### Device Description

ESP32S3 Dev module

### Hardware Configuration

.

### Version

v3.3.10

### Type

Bug

### IDE Name

Arduino IDE 2.3.10

### Operating System

Windows 10 64bit

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Hello,

Until yesterday, I was working with the ESP32 package version 3.3.3 without any issues. After updating to version 3.3.9 or 3.3.10, I get the same error:

Arduino IDE 2.3.10
Board: ESP32-S3 Dev Module

The error appears when I try to compile the sketch.

I have already deleted the `esp32` folder from the packages directory and reinstalled the ESP32 core 2–3 times, but the same error appears every time.

### Sketch

```cpp
.
```

### Debug Message

```plain
fork/exec C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\tools\esp-x32\2601-cn/bin/xtensa-esp32s3-elf-g++.exe: %1 is not a valid Win32 application.

Compilation error: fork/exec C:\Users\Admin\AppData\Local\Arduino15\packages\esp32\tools\esp-x32\2601-cn/bin/xtensa-esp32s3-elf-g++.exe: %1 is not a valid Win32 application.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by gavron04** [comment]
ESET32 internet security shows that exe files from package are infected by WIn64/GenKryptik.HIHM

**Comment by gavron04** [comment]
Ok, finally:
- turn off ESET32,
- delete esp32 package and folder staging
- download again esp32 3.3.10
- install 
and thats all

**Comment by Jason2866** [comment]
Closing since false virus alarm
