### PR TITLE
feat(matter): Arduino Matter with ESP Matter 1.6 and IDF 6.1

### LINKED ISSUE #12851: [Matter] Build fails against esp_matter >=1.6.0: closure-control-cluster-objects.h renamed to ClosureControlClusterObjects.h
### Description

Building any sketch that uses the `Matter` library currently fails when the ESP-IDF Component Manager resolves the latest `espressif/esp_matter` component (`idf_component.yml` only pins `>=1.3.0`, no upper bound, so it resolves to `1.6.0` today).

`libraries/Matter/src/matter_closure_patch.h` includes:

```cpp
#include "app/clusters/closure-control-server/closure-control-cluster-objects.h"
```

In the connectedhomeip snapshot bundled with `esp_matter` 1.6.0, this file was renamed (part of a broader migration of several clusters to the new code-driven `DefaultServerCluster`-based pattern, PascalCase file names):

```
app/clusters/closure-control-server/closure-control-cluster-objects.h  →  app/clusters/closure-control-server/ClosureControlClusterObjects.h
```

This breaks compilation of every Matter endpoint file that transitively includes `Matter.h` (e.g. `MatterGenericSwitch.cpp`, `MatterOnOffLight.cpp`, `MatterDimmableLight.cpp`, `MatterColorTemperatureLight.cpp`, ...):

```
libraries/Matter/src/matter_closure_patch.h:13:10: fatal error: app/clusters/closure-control-server/closure-control-cluster-objects.h: No such file or directory
   13 | #include "app/clusters/closure-control-server/closure-control-cluster-objects.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Reproduction

Build any Matter example as an ESP-IDF component (e.g. `idf_component_examples/Arduino_ESP_Matter_over_OpenThread`) for `esp32c6` with ESP-IDF `release/v5.5`, with no upper version bound on `espressif/esp_matter` in `idf_component.yml` (the default), so the component manager resolves `esp_matter` `1.6.0`.

### Fix

One-line path update:

```diff
-#include "app/clusters/closure-control-server/closure-control-cluster-objects.h"
+#include "app/clusters/closure-control-server/ClosureControlClusterObjects.h"
```

I confirmed this fix builds cleanly against `esp_matter` 1.6.0. Also worth double-checking whether the free-function `operator==` overloads this patch header adds are still needed - `esp_matter` 1.6.0's `ClosureControlClusterObjects.h` already defines a same-type member `operator==` on `GenericOverallCurrentState`/`GenericOverallTargetState`, so the patch may now be partially redundant (didn't hit an ambiguity error in my testing, but worth a look).

### Environment

- Branch: `master` (as of 2026-08-24)
- ESP-IDF: `release/v5.5`
- `espressif/esp_matter`: `1.6.0` (resolved via component manager, no upper bound pinned)
- Target: `esp32c6`

### LINKED ISSUE #12852: [Matter] MatterOccupancySensor.cpp fails to build against esp_matter >=1.6.0: occupancy-sensor-server.h removed, replaced by OccupancySensingCluster
### Description

Same root cause as #12851 (component manager resolving `espressif/esp_matter` `1.6.0` since `idf_component.yml` has no upper bound), but a bigger break: `libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp` includes:

```cpp
#include <app/clusters/occupancy-sensor-server/occupancy-sensor-server.h>
```

This header **no longer exists** in the connectedhomeip snapshot bundled with `esp_matter` 1.6.0:

```
libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp:24:10: fatal error: app/clusters/occupancy-sensor-server/occupancy-sensor-server.h: No such file or directory
   24 | #include <app/clusters/occupancy-sensor-server/occupancy-sensor-server.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Unlike #12851, this isn't a simple file rename - the whole `OccupancySensing::Instance` / `AttributeAccessInterface`-based API that `MatterOccupancySensor.cpp` relies on (`OccupancySensing::Instance`, `OccupancySensing::SetHoldTime`, `OccupancySensing::GetHoldTimeLimitsForEndpoint`, etc., used by the custom `OccupancySensingAttrAccessWrapper` class) has been migrated to a new code-driven `OccupancySensingCluster : public DefaultServerCluster` class, following the same modernization pattern already seen for `ValveConfigurationAndControl` and `ClosureControl`.

The remaining files are:

```
components/esp_matter/data_model/../connectedhomeip/connectedhomeip/src/app/clusters/occupancy-sensor-server/
├── OccupancySensingCluster.h
├── OccupancySensingCluster.cpp
├── CodegenIntegration.h / .cpp
└── README.md
```

### Impact

This blocks the full `arduino-esp32` component build (and hence linking any Matter sketch as an ESP-IDF component) whenever it's built against `esp_matter` `1.6.0`, since `MatterOccupancySensor.cpp` is part of `ARDUINO_LIBRARY_Matter_SRCS` in the root `CMakeLists.txt` and gets compiled unconditionally alongside every other Matter endpoint.

### Suggested fix

`MatterOccupancySensor.cpp`'s `HoldTime`/`HoldTimeLimits` handling (currently done via a custom `AttributeAccessInterface` wrapping `OccupancySensing::Instance`) needs to be rewritten against the new `OccupancySensingCluster` API - likely following the same registry-lookup + direct-method-call pattern already used in this repo for other code-driven clusters (`MatterEndPoint::setBooleanStateValue()` looking up `BooleanStateCluster` via `esp_matter::data_model::provider::get_instance().registry().Get(...)`).

I have not attempted this fix (out of scope for the PR I was working on when I found this) - flagging it separately since it's a real, currently-broken build for anyone building fresh against the latest `esp_matter` component.

### Environment

- Branch: `master` (as of 2026-08-24)
- ESP-IDF: `release/v5.5`
- `espressif/esp_matter`: `1.6.0` (resolved via component manager, no upper bound pinned)
- Target: `esp32c6`

### Related

- #12851 (same root cause, simpler fix)

### LINKED ISSUE #12855: [Matter] esp32-arduino-libs missing Water Valve support (esp_matter needs >=1.6.0)
### Description

Filing here since I don't have write access to open this directly on [`espressif/esp32-arduino-lib-builder`](https://github.com/espressif/esp32-arduino-lib-builder) - please redirect/transfer if there's a better place for it, or feel free to move this to that repo.

**Edit**: my initial report below suggested bumping the `esp_matter` pin to `1.5.1` would fix this. That was wrong - I verified directly against the exact commit used to publish `esp_matter` `1.5.1` and confirmed the `esp_matter` wrapper for Water Valve genuinely does not exist there either. See "What I verified" below for the corrected findings. **The real requirement is `esp_matter` >= 1.6.0.**

`esp32-arduino-lib-builder`'s `main/idf_component.yml` pins:

```yaml
espressif/esp_matter:
  version: "1.5"
  require: public
```

A bare version string with no operator (`^`, `~`, `>=`) is resolved by the ESP-IDF component manager as an **exact match**, so this pins to `esp_matter` `1.5.0` specifically.

### Impact

This blocks [#12853](https://github.com/espressif/arduino-esp32/pull/12853) (`MatterWaterValve`, implementing #12849) from passing this repo's primary `Compilation Tests` CI, which links against the currently published `esp32-arduino-libs-idf-release_v5.5-b774170f-v1.zip` artifact:

```
libraries/Matter/src/MatterEndpoints/MatterWaterValve.cpp:21:10: fatal error:
  app/clusters/valve-configuration-and-control-server/ValveConfigurationAndControlCluster.h: No such file or directory
```

The same code compiles cleanly against `esp_matter` `1.6.0` resolved fresh via the component manager (unrelated to the vendored libs).

### What I verified

Using `espressif/esp-matter`'s own `release/v1.5` branch `CHANGELOG.md`, which gives the exact commits used for each published release:

```
## [1.5.1]
- esp-matter commit: f6dd6eace921ea05bc63dfa957a2486cf1dfb106
- connectedhomeip commit: b87051a95fc110c0cfbac278f232df55c89866de

## [1.5.0]
- esp-matter commit: 92a7abe5166c8e1dd0c1a0d1ceefaeeb71758f9e
- connectedhomeip commit: cf84d0360c48dbc194c48b47b09169f302a9745b
```

Checking the **exact `1.5.1` commit** (`f6dd6eace9...`), not just dates on `main`:

- `espressif/esp-matter`'s own tree at that commit has **zero files** matching `valve` anywhere (`git ls-tree -r`) - no `data_model/generated/device_types/water_valve_device`, no `data_model/generated/clusters/valve_configuration_and_control`, nothing in the legacy cluster layer either. So `esp_matter::endpoint::water_valve` and `esp_matter::cluster::valve_configuration_and_control` (the APIs a Water Valve endpoint needs) genuinely do not exist in `1.5.1`.
- The bundled `connectedhomeip` fork submodule (commit `b87051a95f...`, pinned by `1.5.1`) *does* have the underlying cluster implementation at `src/app/clusters/valve-configuration-and-control-server/`, but under different (older, kebab-case) filenames: `valve-configuration-and-control-cluster.h`/`.cpp`, not `ValveConfigurationAndControlCluster.h`/`.cpp` (the PascalCase names used starting `esp_matter` `1.6.0`, which is what current code needs to include).
- Confusingly, `espressif/esp-matter`'s own `SUPPORTED_DEVICE_TYPES.md` at that same `1.5.1` commit *does* list "Water Valve" as supported - this appears to be inaccurate/aspirational for this release, since there's no corresponding implementation anywhere in the tree at that commit.

So this isn't a simple version-pin float issue (bumping `"1.5"` to `"1.5.1"` would **not** fix it) - the `esp_matter` wrapper API this repo's Matter library relies on for Water Valve was only added starting `esp_matter` `1.6.0`.

The Matter spec device type itself (`WaterValve`, `0x0042`) was introduced in **Matter 1.3** (`data_model/1.3/device_types/WaterValve.xml`, absent from spec `1.2`), for context on how far behind spec vs. SDK support currently is.

### Suggested fix

Bump the `esp_matter` pin in `esp32-arduino-lib-builder`'s `main/idf_component.yml` to `>=1.6.0` (or pin `"1.6.0"` exactly), and publish a new `esp32-arduino-libs` artifact for the `idf-release_v5.5` branch.

### Related

- #12849 (feature request)
- #12853 (the PR this blocks)
- #12851, #12852 (separate, unrelated `esp_matter` 1.6.0 compatibility breaks found while investigating this)

### LINKED ISSUE #12872: error building arduino matter over thread light example for idf v6.0.2
### Board

supermini esp32c6

### Device Description

super mini esp32c6

### Hardware Configuration

No

### Version

latest master (checkout manually)

### Type

Bug

### IDE Name

vscode

### Operating System

windows 11

### Flash frequency

40

### PSRAM enabled

yes

### Upload speed

115200

### Description

compilation terminated

### Sketch

```cpp
idf.py set-target esp32c6
idf.py build
```

### Debug Message

```plain
C:/temp/light 3.3.6/managed_components/espressif__dm9051/include/esp_eth_phy_dm9051.h:10:10: fatal error: esp_eth_com.h: No such file or directory
   10 | #include "esp_eth_com.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[2176/2664] Building C object esp-idf/chmorgan__esp-libhelix-mp3/...df_chmorgan__esp-libhelix-mp3.dir/libhelix-mp3/real/subband.c.obj
ninja: build stopped: subcommand failed.
Missing "esp_eth_com.h" file name found in the following component(s): esp_eth(C:\Users\louis\projecten\esp\v6.0.2\esp-idf\components\esp_eth\include\esp_eth_com.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt. Another possibility may be that the component or its feature is not enabled in the configuration. Use "idf.py menuconfig" to check if the required options are enabled.
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change

It fixes Arduino Matter Library to work with ESP-Matter v1.6 and IDF v6.1, targeting Arduino Core 4.0.x

It depends on https://github.com/espressif/esp32-arduino-lib-builder/pull/402 passing and being used as base.

## Test Scenarios
Tested using Arduino as IDF component and the ESP32-C6. All examples worked as expected.
New testing shall be done using the Arduino IDE and the Libr Builder Artifacts from https://github.com/espressif/esp32-arduino-lib-builder/pull/402

## Related links
Fix #12851 
Fix #12852 
Fix #12855
Fix #12872

### CODE REVIEW

**Comment by SuGlider** [comment]
@me-no-dev -- 

This PR is necessary to allow the [PR #402](https://github.com/espressif/esp32-arduino-lib-builder/pull/402) from Arduino Lib Buider to complete the Jobs.
It removes the include of `matter_closure_patch.h` which is not necessary in ESP-Matter 1.6 and fix many other compilation errors that occur when moving to ESP-Matter 1.6.

This is the egg/chicken problem. One depend on the other to move forward.
From my point of view, this shall be merged even with CI failing.
Then Arduino Lib Buider will be able to build the static libraries. 

Last, I'll get the artifacts and test it locally.
I've done all changes using Arduino as IDF Component based on a local components/arduino-esp32 checked out from release/v4.0.x branch. After getting all working, I have modified the Lib Builder configs based on the local sdkconfig files, plus removing the patch that was added for the Matter 1.5.

File: docs/en/matter/ep_occupancy_sensor.rst [hunk 1]
```diff
@@ -10,8 +10,8 @@ The ``MatterOccupancySensor`` class provides an occupancy sensor endpoint for Ma
 **Features:**
 * Occupancy state reporting (occupied/unoccupied)
 * Multiple sensor type support (PIR, Ultrasonic, Physical Contact)
-* HoldTime attribute (seconds) stored and reportable to controllers
-* HoldTimeLimits (min, max, default) required before a controller can write a non-zero HoldTime
+* Optional HoldTime (seconds). Off unless ``setHoldTime()`` / ``setHoldTimeLimits()`` is called after the sensor ``begin()`` and before ``Matter.begin()``
+* HoldTimeLimits (min, max, default) for controller validation when HoldTime is enabled
```
Comment (pedrominatel) [inline docs/en/matter/ep_occupancy_sensor.rst]: Add a period after each bullet point sentence.

File: docs/en/matter/ep_occupancy_sensor.rst [hunk 2]
```diff
@@ -154,15 +167,14 @@ Sets the HoldTime limits (minimum, maximum, and default values). These limits de
 
     bool setHoldTimeLimits(uint16_t _holdTimeMin_seconds, uint16_t _holdTimeMax_seconds, uint16_t _holdTimeDefault_seconds);
 
-* ``_holdTimeMin_seconds`` - Minimum HoldTime value in seconds
-* ``_holdTimeMax_seconds`` - Maximum HoldTime value in seconds
-* ``_holdTimeDefault_seconds`` - Default/recommended HoldTime value in seconds (informational metadata for controllers)
+* ``_holdTimeMin_seconds`` - Minimum HoldTime value in seconds (CHIP coerces values below 1 up to 1)
```
Comment (pedrominatel) [inline docs/en/matter/ep_occupancy_sensor.rst]: Add a period.

File: docs/en/matter/ep_occupancy_sensor.rst [hunk 3]
```diff
@@ -250,7 +262,7 @@ For an example that demonstrates HoldTime functionality, see:
     :language: arduino
 
 This example shows:
-* How to configure HoldTimeLimits after ``Matter.begin()``
-* How to set and persist HoldTime values
+* How to configure HoldTimeLimits and HoldTime after the sensor ``begin()`` and before ``Matter.begin()``
```
Comment (pedrominatel) [inline docs/en/matter/ep_occupancy_sensor.rst]: Check all bullet points with sentences without periods.

File: docs/en/matter/ep_window_covering.rst [hunk 4]
```diff
@@ -442,6 +442,8 @@ Gets the current target lift position in percent100ths.
 
 This function will return the current target lift position in percent100ths (0-10000).
 
+``onGoToLiftPercentage()`` runs in PRE_UPDATE, so a cluster read would still be the previous Target. This getter returns the incoming request (cached from the write), which is the value to copy into Current for an instant move.
```
Comment (pedrominatel) [inline docs/en/matter/ep_window_covering.rst]: I see capital letters being used inconsistently in different places, such as `Target` and `Current`. Could you please review this?

I think it will be clearer if you change it to `current lift position`.

File: docs/en/matter/ep_occupancy_sensor.rst (hunk 1 above)
Comment (SuGlider) [reply docs/en/matter/ep_occupancy_sensor.rst]: All bullets fixed with https://github.com/espressif/arduino-esp32/pull/12913/changes/8b7660b2277853f67e34a07a7d3648b6629d634a

File: docs/en/matter/ep_occupancy_sensor.rst (hunk 2 above)
Comment (SuGlider) [reply docs/en/matter/ep_occupancy_sensor.rst]: All bullets fixed with https://github.com/espressif/arduino-esp32/pull/12913/changes/8b7660b2277853f67e34a07a7d3648b6629d634a

File: docs/en/matter/ep_occupancy_sensor.rst (hunk 3 above)
Comment (SuGlider) [reply docs/en/matter/ep_occupancy_sensor.rst]: All bullets fixed with https://github.com/espressif/arduino-esp32/pull/12913/changes/8b7660b2277853f67e34a07a7d3648b6629d634a

File: docs/en/matter/ep_window_covering.rst (hunk 4 above)
Comment (SuGlider) [reply docs/en/matter/ep_window_covering.rst]: fixed with https://github.com/espressif/arduino-esp32/pull/12913/changes/8b7660b2277853f67e34a07a7d3648b6629d634a

Comment (SuGlider) [reply docs/en/matter/ep_window_covering.rst]: There is an important difference between Target and Current for this endpoint.

I clarified the next paragraph with attribute names and “current lift position” in prose. Target and current are two Matter attributes (TargetPositionLiftPercent100ths vs CurrentPositionLiftPercent100ths) and are managed separately; line 443 is only the getter return value, and the PRE_UPDATE/cache behavior is explained right below it.

**Review by pedrominatel — APPROVED** [review]
