### ISSUE TITLE
When will IDE offer full support of MIPI-CSI (with integrated Image Signal Processor) and MIPI-DSI for ESP32-P4 boards?

### ISSUE THREAD

**Issue by papagino007** [espressif/arduino-esp32#12205]
### Related area

ESP32-P4 MIPI-CSI & MIPI-DSI support

### Hardware specification

Waveshare ESP32-P4-ETH

### Is your feature request related to a problem?

No MIPI-CSI & MIPI-DSI support...

### Describe the solution you'd like

Support for MIPI-CSI & MIPI-DSI on ESP32-P4 Development boards

### I have checked existing list of Feature requests and the Contribution Guide

- [x] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by lyusupov** [comment]
MIPI-DSI on ESP32-P4 is provided by Espressif Display driver and GUI porting library

https://github.com/esp-arduino-libs/ESP32_Display_Panel

**Comment by papagino007** [comment]
Thanks, but it is the MIPI-CSI (camera) portion that I need for my project. I am currently trying to have this work using my arduino code in ESP-IDF v5.5.2 as component and using the "simple_video_server" example bits inside VS Code. It would be nice to have Arduino IDE to have also support for MIPI-CSI and MIPI-DSI for ESP32-P4 boards.
Cheers

**Comment by liampclark** [comment]
https://github.com/espressif/arduino-esp32/issues/11695

id also like to have this

**Comment by EIKSEU** [comment]
Hello, have you had any success with your project? I would also like to get a P4 Nano running with the OV5647 using the Arduino.ide...

**Comment by papagino007** [comment]
> Hello, have you had any success with your project? I would also like to get a P4 Nano running with the OV5647 using the Arduino.ide...

I placed the project on hold for now waiting for IDE to fully support the P4.
If IDE doesn't come up with better support in a couple months, then I might try to got the full IDF route...
Cheers

**Comment by papagino007** [comment]
... still Awaiting Response

**Comment by TheZeroHz** [comment]
Hey, @lyusupov  @papagino007  @EIKSEU  @liampclark  while we wait on official CSI support in the IDE, I built an Arduino library for ESP32-P4 MIPI-CSI that already runs on the current arduino-esp32 core. I’ve been using it with **OV5647** and **IMX708**.

https://github.com/TheZeroHz/ESP32CSI_Vision

Install it, enable PSRAM, and check the examples. Happy to help if you hit issues.

**Comment by me-no-dev** [comment]
ESP-Video library was released with 3.3.11

**Comment by papagino007** [comment]
Yessss,, it is working... Great...

**Comment by EIKSEU** [comment]
Hello @TheZeroHz,
Thanks for your library.
I would like to use WiFiMjpeg.ino (Waveshare ESP32 P4 Nano), but unfortunately, I keep getting the following error message during compilation:
.....\Arduino\libraries\ESP32CSI_Vision\src\espdl\human_face_detect\human_face_detect.hpp:3:10: fatal error: dl_detect_base.hpp: No such file or directory
    3 | #include "dl_detect_base.hpp"
Could you please help me with this?

**Comment by TheZeroHz** [comment]
Hi, @EIKSEU  thanks for using the library and for reporting this.

Sorry about the confusion — I had already shared an updated package earlier, but I missed pushing that same source update to GitHub. The `dl_detect_base.hpp` include error comes from that mismatch (Arduino needs the ESP-DL include wrappers under `src/`).

I’ve now pushed the latest source to the **main** branch. Please:

1. Pull / re-download **ESP32CSI_Vision** from [github.com/thezerohz/ESP32CSI_Vision](https://github.com/thezerohz/ESP32CSI_Vision) (main)
2. Replace the copy in `Documents/Arduino/libraries/ESP32CSI_Vision` (delete the old folder first so leftover files don’t mix)
3. Restart Arduino IDE and compile `WiFiMjpeg.ino` again

Also please confirm your **Arduino-ESP32 core** version:

- Required: **Arduino-ESP32 3.3.x** (Board Manager → `esp32` by Espressif)
- Board: **ESP32P4 Dev Module**
- PSRAM: **Enabled**
- Partition: a large app scheme such as `app3M_fat9M_16MB` (16MB flash)

This library targets ESP32-P4 + PSRAM on Arduino-ESP32 3.3.x. Older 2.x / early 3.x cores will not build.

After updating the library from main and checking the core version, the Waveshare ESP32-P4 Nano `WiFiMjpeg` example should compile. If anything still fails, send the full compiler log.

Thanks again.

**Comment by lyusupov** [comment]
@TheZeroHz 

Thank you for the library!

I've tried your `01_CamTest` with OV2710 camera _( LilyGO T-Display P4 )_

The camera settings are default ones except SDA/SCL pins:

```
  esp32p4_cam_config_t c{};
  c.sda = 20;
  c.scl = 21;
  c.xclk = -1;
  c.pwdn = -1;
  c.reset = -1;
  c.xclk_hz = 24000000;
  c.i2c_addr = 0;
  c.ldo_chan = 3;
  c.ldo_mv = 2500;
  c.frame_size = ESP32P4_FRAMESIZE_AUTO;
  c.pixel_format = ESP32P4_PIXFORMAT_RGB565;
  c.lane_bit_rate_mbps = 0;  // auto from mode
  c.sensor = ESP32P4_SENSOR_AUTO;
  c.test_pattern = false;
  c.fb_count = 3;  // 1 held by app + 1 CSI + 1 spare (prevents mid-frame tear)
```

The test gives `capture timeout`

```
=== 01_CamTest ===
CSI: begin AUTO probe â€” see Serial for registry hits
CHIP_REV=0x80 DISCH=0x00 FUNC=0x00 SEQ_DV=0x00 SEQ_AV=0x00 EN=0x0D SEQ_CTRL=0x00
DVDD1 reg=0x7C (1496 mV, enabled), DVDD2 reg=0x57 (1200 mV, disabled)
AVDD1 reg=0x27 (1696 mV, enabled), AVDD2 reg=0xCA (3000 mV, enabled)
CSI: PSRAM ok  free=33549568CSI: I2C scan SDA=20 SCL=21  registry=26 sensors  ack 0x18  ack 0x28  ack 0x36  ack 0x58  ack 0x68CSI: 0x36 present but id=0x2710 (not OV5647)CSI: probed OV2710 @ 0x36 (experimental)CSI: OV2710 mode OV2710 1920x1080  1920x1080  lanes=1  800 Mbps/lane  isp=1CSI: 3 PSRAM framebuffers x 4147200 bytes (PSRAM free=21107920)CSI: ISP RAW->RGB565 + demosaic (clk=160 MHz bayer=3)CSI: controller started 1920x1080  1-lane @ 800 Mbps/laneCSI: streaming 1920x1080 RGB565CSI: OV2710 @ 0x36  1920x1080  lanes=1
capture timeout
capture timeout
capture timeout
capture timeout
```

Any ideas how to fix it ?

**Comment by TheZeroHz** [comment]
Hi @lyusupov, thanks for trying the library, and thanks for the log.

Your camera is found (OV2710 at `0x36`) and CSI starts. The problem is that **no frames arrive**, so you get `capture timeout`.

This looks like a bug in my OV2710 driver. After init the sensor stays in sleep. I used the wrong register to start it (`0x0100`). OV2710 needs a different wake sequence.

Please try this debug sketch on your T-Display P4. Open Serial at **115200**, then copy the log back here. Tell me if you get frames or still get timeout. I will use that to fix it in the library.

```cpp
#include <ESP32CSI_Vision.h>
#include <Wire.h>

// LilyGO T-Display P4 camera I2C pins
static const int CAM_SDA = 20;
static const int CAM_SCL = 21;
static const uint8_t OV2710_ADDR = 0x36;

ESP32P4_Camera cam;

bool ov2710Write(uint16_t reg, uint8_t value) {
  Wire.beginTransmission(OV2710_ADDR);
  Wire.write((uint8_t)(reg >> 8));
  Wire.write((uint8_t)reg);
  Wire.write(value);
  return Wire.endTransmission() == 0;
}

bool ov2710Read(uint16_t reg, uint8_t *value) {
  if (!value) return false;
  Wire.beginTransmission(OV2710_ADDR);
  Wire.write((uint8_t)(reg >> 8));
  Wire.write((uint8_t)reg);
  if (Wire.endTransmission(false) != 0) return false;
  if (Wire.requestFrom((int)OV2710_ADDR, 1) != 1) return false;
  *value = (uint8_t)Wire.read();
  return true;
}

void printReg(const char *name, uint16_t reg) {
  uint8_t value = 0;
  if (ov2710Read(reg, &value)) {
    Serial.printf("  %s (0x%04X) = 0x%02X\n", name, reg, value);
  } else {
    Serial.printf("  %s (0x%04X) READ FAILED\n", name, reg);
  }
}

void wakeOv2710() {
  Serial.println();
  Serial.println("=== OV2710 wake (workaround) ===");
  Serial.println("Before wake (expect 0x3008=0x42):");
  printReg("SLEEP/STREAM", 0x3008);
  printReg("FRAME_CTRL", 0x4202);
  Serial.printf("  CSI trans=%u  done=%u\n", cam.newTransCount(), cam.doneCount());

  Serial.println("Writing wake sequence...");
  ov2710Write(0x4201, 0x00);
  ov2710Write(0x4202, 0x00);
  ov2710Write(0x3008, 0x02);
  delay(200);

  Serial.println("After wake (expect 0x3008=0x02, 0x4202=0x00):");
  printReg("SLEEP/STREAM", 0x3008);
  printReg("FRAME_CTRL", 0x4202);
  Serial.printf("  CSI trans=%u  done=%u\n", cam.newTransCount(), cam.doneCount());
  Serial.println("=== wake done, capturing... ===");
  Serial.println();
}

void setup() {
  Serial.begin(115200);
  delay(1200);
  Serial.println("=== OV2710 debug (LilyGO T-Display P4) ===");

  esp32p4_cam_config_t cfg = esp32p4_cam_config_default();
  cfg.sda = CAM_SDA;
  cfg.scl = CAM_SCL;
  cfg.xclk = -1;
  cfg.pwdn = -1;
  cfg.reset = -1;
  cfg.xclk_hz = 24000000;
  cfg.i2c_addr = 0;
  cfg.ldo_chan = 3;
  cfg.ldo_mv = 2500;
  cfg.frame_size = ESP32P4_FRAMESIZE_AUTO;
  cfg.pixel_format = ESP32P4_PIXFORMAT_RGB565;
  cfg.lane_bit_rate_mbps = 0;
  cfg.sensor = ESP32P4_SENSOR_OV2710;
  cfg.test_pattern = false;
  cfg.fb_count = 3;

  Serial.println("Starting camera...");
  if (!cam.begin(cfg)) {
    Serial.println("ERROR: camera begin FAILED");
    while (true) delay(1000);
  }

  Serial.printf("OK: %s @ 0x%02X  %ux%u  lanes=%u\n", cam.sensorName(),
                cam.sensorAddress(), cam.width(), cam.height(),
                (unsigned)cam.dataLanes());

  wakeOv2710();
}

void loop() {
  camera_fb_t *fb = cam.capture(2000);
  if (!fb) {
    Serial.printf("capture timeout  trans=%u  done=%u\n",
                  cam.newTransCount(), cam.doneCount());
    return;
  }

  uint32_t sum = 0;
  size_t pixels = fb->len / 2;
  const uint16_t *p = (const uint16_t *)fb->buf;
  size_t step = pixels > 2048 ? pixels / 2048 : 1;
  size_t samples = 0;
  for (size_t i = 0; i < pixels; i += step) {
    sum += p[i];
    samples++;
  }

  Serial.printf("OK frame %ux%u  mean=%u  trans=%u  done=%u  psram_free=%u\n",
                fb->width, fb->height,
                (unsigned)(samples ? sum / samples : 0),
                cam.newTransCount(), cam.doneCount(),
                (unsigned)esp32p4_psram_free_size());
  cam.release(fb);
}
```

**Please reply with:**

1. Did it work? (`OK frame` = yes, `capture timeout` = no)
2. Copy/paste these Serial lines:
   - `Before wake`
   - `After wake`
   - a few `OK frame` or `capture timeout trans=… done=…` lines

If it works, I will add this wake sequence into the library. If not, your log will help me find the next issue. Thanks!

**Comment by lyusupov** [comment]
@TheZeroHz 

Here is the log

```
=== OV2710 debug (LilyGO T-Display P4) ===

Starting camera...

CSI: PSRAM ok  free=33549824
CSI: I2C scan SDA=20 SCL=21  registry=26 sensors
  ack 0x18
  ack 0x28
  ack 0x36
  ack 0x58
  ack 0x68
CSI: OV2710 mode OV2710 1920x1080  1920x1080  lanes=1  800 Mbps/lane  isp=1
CSI: 3 PSRAM framebuffers x 4147200 bytes (PSRAM free=21107920)
CSI: ISP RAW->RGB565 + demosaic (clk=160 MHz bayer=3)
CSI: controller started 1920x1080  1-lane @ 800 Mbps/lane
CSI: streaming 1920x1080 RGB565
OK: OV2710 @ 0x36  1920x1080  lanes=1

=== OV2710 wake (workaround) ===

Before wake (expect 0x3008=0x42):

  SLEEP/STREAM (0x3008) = 0x42
  FRAME_CTRL (0x4202) = 0x0F
  CSI trans=1  done=0
Writing wake sequence...

After wake (expect 0x3008=0x02, 0x4202=0x00):

  SLEEP/STREAM (0x3008) = 0x02
  FRAME_CTRL (0x4202) = 0x00
  CSI trans=6  done=5
=== wake done, capturing... ===

OK frame 1920x1080  mean=26  trans=6  done=5  psram_free=18515444
OK frame 1920x1080  mean=58  trans=7  done=6  psram_free=18515444
OK frame 1920x1080  mean=79  trans=8  done=7  psram_free=18515444
OK frame 1920x1080  mean=6557  trans=9  done=8  psram_free=18515444
OK frame 1920x1080  mean=6543  trans=10  done=9  psram_free=18515444

```

**Comment by lyusupov** [comment]
@TheZeroHz 

I can confirm that after I've added `wakeOv2710()` at the end of `01_CamTest`  setup() sequence
the `01_CamTest`  sketch has started to work properly

```
1920x1080 mean=27 psram_free=18515444
1920x1080 mean=216 psram_free=18515444
1920x1080 mean=243 psram_free=18515444
1920x1080 mean=8212 psram_free=18515444
1920x1080 mean=8194 psram_free=18515444
1920x1080 mean=15562 psram_free=18515444
1920x1080 mean=15539 psram_free=18515444
```

**Comment by TheZeroHz** [comment]
Hi @lyusupov, thanks a lot for the confirmation.

I’ve updated the library with this fix. OV2710 now wakes correctly inside `cam.begin()`, so you can remove `wakeOv2710()` from your sketch.

Please pull the latest **main** (v3.5.1) and run the normal `01_CamTest` with your SDA=20 / SCL=21 settings.

Thanks again for testing on the T-Display P4.

**Comment by lyusupov** [comment]
@TheZeroHz 

I can see in your code 
1) https://github.com/TheZeroHz/ESP32CSI_Vision/blob/main/src/cam/ESP32P4_Camera.cpp#L229-L238 
2) https://github.com/TheZeroHz/ESP32CSI_Vision/blob/main/src/cam/esp32p4_sccb.cpp

that you explicitly use `Wire` instance in the library, right?
This is not convenient, because some P4 boards use two IIC buses. **Camera is connected to 2nd bus**.
It makes sense to give an option for a user to choose `Wire1` as an argument.

**Comment by EIKSEU** [comment]
Hi @TheZeroHz, the stream is running now! Thanks. Can I also include the audio from the stream?

**Comment by TheZeroHz** [comment]
> [@TheZeroHz](https://github.com/TheZeroHz)
> 
> I can see in your code
> 
> 1. https://github.com/TheZeroHz/ESP32CSI_Vision/blob/main/src/cam/ESP32P4_Camera.cpp#L229-L238
> 2. https://github.com/TheZeroHz/ESP32CSI_Vision/blob/main/src/cam/esp32p4_sccb.cpp
> 
> that you explicitly use `Wire` instance in the library, right? This is not convenient, because some P4 boards use two IIC buses. **Camera is connected to 2nd bus**. It makes sense to give an option for a user to choose `Wire1` as an argument.

Hi @lyusupov, really appreciate you taking the time to look through the code and point this out.

You’re absolutely right. I hardcoded `Wire`, and that was a silly mistake. On boards like the T-Display P4 with two I2C buses, the camera belongs on the second bus. Your note was spot on, and it helped a lot.

I’ve fixed it in **v3.5.1**. You can now pass `Wire1`; existing sketches still default to `Wire`.

```cpp
esp32p4_cam_config_t c = esp32p4_cam_config_default();
c.sda = 20;
c.scl = 21;
c.wire = &Wire1;  // camera on I2C1
cam.begin(c);
```

Please pull the latest **main** when you have a chance. Thank you again for the careful review and for all the testing you’ve already done on this board  it’s been a huge help.

**Comment by lyusupov** [comment]
@TheZeroHz 

Thank you!

I have a misc. question -

you specify _( above )_ that pixel_format = ESP32P4_PIXFORMAT_RGB565 for **OV2710**

<img width="622" height="225" alt="Image" src="https://github.com/user-attachments/assets/385b5e7b-2ea7-4213-953b-8ab7a4c3b447" />

<br>
<br>

However [the docs](https://github.com/TheZeroHz/ESP32CSI_Vision/blob/main/docs/CSI-Cameras.md#sensor-matrix) say that 

<img width="1668" height="117" alt="Image" src="https://github.com/user-attachments/assets/ff3d91f0-1898-49fb-adaa-6368cb24a367" />

<br>
<br>

Is it Ok to keep `ESP32P4_PIXFORMAT_RGB565`  or should I change it to `ESP32P4_PIXFORMAT_RAW10` for **OV2710**  ?

**Comment by papagino007** [comment]
That is great development, any idea when ESP32CSI_Vision will adds full IMX477 or IMX462 support?

**Comment by TheZeroHz** [comment]
@papagino007  I'm already working on it. I may release it within the next 24 hours.

In this version, I'll try to add:

* Maximum possible camera support (DVP, CSI, USB, SPI, etc.)
* Live video + microphone streaming
* ESP-DL model integration
* Fix several minor issues and improve stability

In this regard, I'd really appreciate your help in testing and verifying that the library works properly across different boards and camera configurations. 

@lyusupov  @papagino007  @EIKSEU

**Comment by TheZeroHz** [comment]
Update from **ESP32CSI_Vision v3.25.0**: https://github.com/TheZeroHz/ESP32CSI_Vision/releases/tag/v3.25.0

What landed since the last notes in this thread:

- **IMX477 / IMX462** CSI, plus DVP, SPI, USB UVC gadget/host
- **Live video + mic**: `29_WiFiMjpegWaveshareNano`, `30_EthLiveAvFiles`, `31_WiFiLiveAvFiles`
- **ESP-DL zoo** on Arduino: COCO / YOLO26 / pose / seg / OCR / gesture / ImageNet (examples `32`–`43`)
- Camera and ES8311 can use **`Wire1`** (`cfg.wire`)
- OV2710 wake and the `dl_detect_base.hpp` compile fix are unchanged
- Per-example `board_config.h` for Waveshare Nano, LilyGO, Guition, and custom boards

Arduino-ESP32 **3.3.x**, PSRAM enabled, large app partition. Happy to help if a given board still fails.

**Comment by papagino007** [comment]
ok, when installing the new library ESP32CSI_Vision v3.25.0 using the latest Board Manager esp32 by Expressif Systems version 4.0.0a, it will not compile, I get ...\Documents\Arduino\libraries\ESP32CSI_Vision\src\cam\ESP32P4_Camera.cpp:17:10: fatal error: esp_cam_sensor_types.h: No such file or directory
   17 | #include "esp_cam_sensor_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

It was working fine with v3.5.1...

**Comment by papagino007** [comment]
... here is a break down:  

ESP32CSI_Vision v3.25.0
Arduino IDE
Arduino-ESP32 4.0.0-alpha1
ESP32-P4

Compile fails in:
src/cam/ESP32P4_Camera.cpp:17

fatal error:
esp_cam_sensor_types.h: No such file or directory

library.properties has no depends= entry for esp_cam_sensor.
Is esp_cam_sensor supposed to be bundled with the Arduino ZIP,
or is v3.25.0 currently intended for ESP-IDF/component-manager builds only?
