### ISSUE TITLE
missing GPIO.in and GPIO.out in release 3.0

### ISSUE THREAD

**Issue by dsilletti** [espressif/arduino-esp32#8846]
### Board

ESP32S3

### Device Description

DevKitC

### Hardware Configuration

N/A

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

MacOS

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

GPIO.in and GPIO.out are not working in release 3.0.
digitalRead and digitalWrite or gpio_get_level and gpio_set_level are too slow for my application.

### Sketch

```cpp
if( (GPIO.in >> 3) & 0x1) ets_printf("GPIO3 HIGH");
```

### Debug Message

```plain
Compilation error: 'GPIO' was not declared in this scope
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by dsilletti** [comment]
Fixed, in release 3.0 I need to include "soc/gpio_struct.h", in 2.x was not needed.
