### ISSUE TITLE
after 2.0.7 update (from 2.0.6) compilation error

### ISSUE THREAD

**Issue by PrintableProps** [espressif/arduino-esp32#7977]
### Board

ESP32 WROOM Dev Kit

### Device Description

plain module on breadboard

### Hardware Configuration

no

### Version

v2.0.7

### IDE Name

Arduino IDE

### Operating System

Mac OS

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

After updating to 2.0.7 I get the following Error Message. I'm not a Pro in programming so I don't really know what the error message means.

Also (maybe off topic): I was running 2.0.6 which worked but I wasn't able to use UART serial2. The serial0 baudrate seems to "block" serial2. Any ideas / tips about that?

### Sketch

```cpp
cant compile
```

### Debug Message

```plain
bash: line 1: 91515 Segmentation fault: 11  "/Users/pascalboecker/Library/Arduino15/packages/esp32/tools/esptool_py/4.5.1"/esptool --chip esp32 elf2image --flash_mode dio --flash_freq 80m --flash_size 4MB -o "/private/var/folders/db/p4r4g7jd52v8cpzgl264bbxr0000gn/T/arduino/sketches/24FB0DA8DA54FF1FFA7510917ECAA5EE"/HSTest.ino.bootloader.bin "/Users/pascalboecker/Library/Arduino15/packages/esp32/hardware/esp32/2.0.7"/tools/sdk/esp32/bin/bootloader_qio_80m.elf

exit status 139

Compilation error: exit status 139
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment]
Hello,

we are aware of this issue and it's probably duplicate of https://github.com/espressif/arduino-esp32/issues/7923.

There will be release of version of 2.0.8 soon.
